"""Structural conversion-rule seeds (beyond 1:1 function mappings).

These encode the Section 6 realism constraints explicitly:
* nested LODs / table-calc-on-table-calc capped at ASSISTED;
* Qlik alternate states are MANUAL (bookmark / field-parameter redesign);
* Spotfire OVER with custom hierarchies is ASSISTED with mandatory review.

Tuple shape mirrors ConversionRule:
(rule_id, source_tool, source_pattern, source_example, dax_template,
 dax_example, confidence, preconditions, known_failure_modes)
"""

PATTERN_RULES: list[tuple] = [
    # ---------------- Tableau LOD ----------------
    (
        "tab-lod-fixed",
        "tableau",
        r"ast:lod-fixed",
        "{ FIXED [Customer] : SUM([Sales]) }",
        "CALCULATE({expr}, ALLEXCEPT({table}, {dims}))",
        "CALCULATE(SUM(Sales[Sales]), ALLEXCEPT(Sales, Sales[Customer]))",
        0.82,
        ["dimension columns resolve to a single table"],
        ["row-context usage differs from filter-context", "FIXED ignores some filters that ALLEXCEPT keeps"],
    ),
    (
        "tab-lod-fixed-nodim",
        "tableau",
        r"ast:lod-fixed-empty",
        "{ FIXED : SUM([Sales]) }",
        "CALCULATE({expr}, REMOVEFILTERS())",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS())",
        0.88,
        [],
        ["context filters in Tableau still apply to FIXED"],
    ),
    (
        "tab-lod-include",
        "tableau",
        r"ast:lod-include",
        "{ INCLUDE [Region] : AVG([Sales]) }",
        "AVERAGEX(VALUES({dim}), CALCULATE({expr}))",
        "AVERAGEX(VALUES(Sales[Region]), CALCULATE(SUM(Sales[Sales])))",
        0.72,
        ["outer aggregation re-applied by the visual"],
        ["double-aggregation mismatch when the outer agg differs from the visual's"],
    ),
    (
        "tab-lod-exclude",
        "tableau",
        r"ast:lod-exclude",
        "{ EXCLUDE [Month] : SUM([Sales]) }",
        "CALCULATE({expr}, REMOVEFILTERS({dims}))",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS(Sales[Month]))",
        0.78,
        [],
        ["EXCLUDE interacts with table-calc filters differently"],
    ),
    (
        "tab-lod-nested",
        "tableau",
        r"ast:lod-nested",
        "{ FIXED [A] : SUM({ INCLUDE [B] : MAX([X]) }) }",
        None,
        "-- nested LOD: composed CALCULATE/iterator chain, mandatory review",
        0.62,
        ["manual review of filter-context interaction"],
        ["nested context transitions rarely match 1:1", "performance of nested iterators"],
    ),
    (
        "tab-tc-on-tc",
        "tableau",
        r"ast:tablecalc-nested",
        "WINDOW_SUM(RUNNING_SUM(SUM([Sales])))",
        None,
        "-- table-calc-on-table-calc: composed WINDOW chain, mandatory review",
        0.60,
        ["explicit ORDERBY axis"],
        ["addressing/partitioning has no DAX analogue"],
    ),
    (
        "tab-pct-of-total",
        "tableau",
        r"(?i)SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*/\s*TOTAL\s*\(\s*SUM\s*\(\s*\[\1\]\s*\)\s*\)",
        "SUM([Sales]) / TOTAL(SUM([Sales]))",
        "DIVIDE(SUM('{table}'[{0}]), CALCULATE(SUM('{table}'[{0}]), ALLSELECTED()))",
        "DIVIDE(SUM(Sales[Sales]), CALCULATE(SUM(Sales[Sales]), ALLSELECTED()))",
        0.85,
        [],
        ["ALLSELECTED scope vs Tableau 'table (across)' scope"],
    ),
    # ---------------- Qlik set analysis ----------------
    (
        "qlik-set-field-value",
        "qlikview",
        r"ast:set-field-eq",
        "Sum({<Year={2024}>} Sales)",
        "CALCULATE(SUM({col}), {field} = {value})",
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = 2024)",
        0.85,
        [],
        ["search strings and wildcards in the element set"],
    ),
    (
        "qlik-set-exclude",
        "qlikview",
        r"ast:set-field-exclude",
        "Sum({<Region-={'EU'}>} Sales)",
        "CALCULATE(SUM({col}), {field} <> {value})",
        'CALCULATE(SUM(Sales[Sales]), Sales[Region] <> "EU")',
        0.82,
        [],
        ["multi-value exclusion needs NOT...IN pattern"],
    ),
    (
        "qlik-set-clear-field",
        "qlikview",
        r"ast:set-field-clear",
        "Sum({<Year=>} Sales)",
        "CALCULATE(SUM({col}), REMOVEFILTERS({field}))",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS(Sales[Year]))",
        0.88,
        [],
        [],
    ),
    (
        "qlik-set-all",
        "qlikview",
        r"ast:set-ignore-all",
        "Sum({1} Sales)",
        "CALCULATE(SUM({col}), REMOVEFILTERS())",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS())",
        0.88,
        [],
        ["{1} ignores selections but respects nothing else; ALL vs ALLSELECTED choice"],
    ),
    (
        "qlik-set-dollar-expansion",
        "qlikview",
        r"ast:set-dollar",
        "Sum({<Year={$(vMaxYear)}>} Sales)",
        None,
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = [Max Year Value])  -- via measure/what-if",
        0.65,
        ["variable resolves to a measure or what-if parameter"],
        ["dollar expansions executing arbitrary expressions"],
    ),
    (
        "qlik-set-element-func",
        "qlikview",
        r"ast:set-pe-func",
        "Sum({<Customer=P({<Year={2024}>} Customer)>} Sales)",
        None,
        "CALCULATE(SUM(Sales[Sales]), CALCULATETABLE(VALUES(Sales[Customer]), Sales[Year]=2024))",
        0.62,
        ["review filter direction"],
        ["E() exclusion sets invert subtly"],
    ),
    (
        "qlik-alternate-state",
        "qlikview",
        r"ast:set-alternate-state",
        "Sum({State1<Year={2024}>} Sales)",
        None,
        "-- no DAX equivalent: redesign with bookmarks / field parameters / calc groups",
        0.30,
        [],
        ["alternate states have no Power BI filter-context analogue"],
    ),
    (
        "qlik-aggr",
        "qlikview",
        r"ast:aggr",
        "Avg(Aggr(Sum(Sales), Customer))",
        'AVERAGEX(SUMMARIZE({table}, {dims}, "@v", {expr}), [@v])',
        'AVERAGEX(SUMMARIZE(Sales, Sales[Customer], "@v", CALCULATE(SUM(Sales[Sales]))), [@v])',
        0.72,
        ["Aggr dimensions resolve to model columns"],
        ["nested Aggr", "Aggr with sort-weight arguments"],
    ),
    (
        "qlik-total-qualifier",
        "qlikview",
        r"(?i)\b(Sum|Avg|Min|Max|Count)\s*\(\s*TOTAL\b",
        "Sum(TOTAL Sales)",
        "CALCULATE({agg}({col}), ALLSELECTED())",
        "CALCULATE(SUM(Sales[Sales]), ALLSELECTED())",
        0.82,
        [],
        ["TOTAL <dims> qualified form needs ALLEXCEPT instead"],
    ),
    (
        "qlik-interrecord-chart",
        "qlikview",
        r"(?i)\b(Above|Below)\s*\(",
        "Sum(Sales) / Above(Sum(Sales))",
        None,
        "DIVIDE([Sales], CALCULATE([Sales], OFFSET(-1, ORDERBY('Date'[Month]))))",
        0.60,
        ["explicit ORDERBY axis"],
        ["visual sort order vs ORDERBY mismatch"],
    ),
    # ---------------- Qlik Sense specifics ----------------
    (
        "qs-master-measure",
        "qliksense",
        r"ast:master-measure",
        "Master measure 'Total Sales'",
        "{expr}",
        "Total Sales = SUM(Sales[Sales])  -- becomes a model measure",
        0.90,
        [],
        [],
    ),
    (
        "qs-variable-expansion",
        "qliksense",
        r"\$\(\w+\)",
        "$(vDiscount) * Sum(Sales)",
        None,
        "-- variable: map to what-if parameter or measure; review each expansion",
        0.60,
        ["variable is a constant or simple expression"],
        ["variables containing expression fragments (token splicing)"],
    ),
    # ---------------- Spotfire ----------------
    (
        "spot-over-all",
        "spotfire",
        r"ast:over-all",
        "Sum([Sales]) OVER (All([Axis.X]))",
        "CALCULATE({expr}, ALLSELECTED({dim}))",
        "CALCULATE(SUM(Sales[Sales]), ALLSELECTED(Sales[Region]))",
        0.80,
        [],
        ["Axis.X binding must be resolved to a model column"],
    ),
    (
        "spot-over-allprevious",
        "spotfire",
        r"ast:over-allprevious",
        "Sum([Sales]) OVER (AllPrevious([Axis.X]))",
        "CALCULATE({expr}, FILTER(ALLSELECTED({dim}), {dim} <= MAX({dim})))",
        "CALCULATE(SUM(Sales[Sales]), FILTER(ALLSELECTED('Date'[Month]), 'Date'[Month] <= MAX('Date'[Month])))",
        0.75,
        ["axis column is ordered"],
        ["categorical (non-ordered) axes"],
    ),
    (
        "spot-over-intersect-custom",
        "spotfire",
        r"ast:over-intersect-hierarchy",
        "Sum([Sales]) OVER (Intersect([Hier1], AllPrevious([Axis.X])))",
        None,
        "-- OVER with custom hierarchies: ASSISTED, mandatory review",
        0.60,
        ["hierarchy levels exist as model columns"],
        ["custom hierarchy slicing has no direct filter-context analogue"],
    ),
    (
        "spot-then",
        "spotfire",
        r"(?i)\bTHEN\b",
        "Sum([Sales]) THEN [Value] / Max([Value]) OVER (All([Axis.X]))",
        None,
        "-- THEN post-aggregation: chain via VARs in one measure; review",
        0.60,
        [],
        ["multi-stage THEN chains"],
    ),
    (
        "spot-case",
        "spotfire",
        r"(?i)\bCASE\s+WHEN\b",
        "CASE WHEN [Sales] > 100 THEN 'High' ELSE 'Low' END",
        "SWITCH(TRUE(), {cond1}, {val1}, {default})",
        'SWITCH(TRUE(), Sales[Sales] > 100, "High", "Low")',
        0.88,
        [],
        [],
    ),
    # ---------------- cross-cutting time intelligence ----------------
    (
        "xx-ytd",
        "tableau",
        r"(?i)RUNNING_SUM\s*\(\s*SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*\)",
        "RUNNING_SUM(SUM([Sales])) partitioned by year",
        "TOTALYTD(SUM('{table}'[{0}]), 'Date'[Date])",
        "TOTALYTD(SUM(Sales[Sales]), 'Date'[Date])",
        0.70,
        ["requires marked date table", "partition is calendar year"],
        ["running totals not aligned to calendar periods"],
    ),
    (
        "xx-moving-avg",
        "tableau",
        r"(?i)WINDOW_AVG\s*\(\s*SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*,\s*-(\d+)\s*,\s*0\s*\)",
        "WINDOW_AVG(SUM([Sales]), -2, 0)",
        "AVERAGEX(DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -{1}, MONTH), CALCULATE(SUM('{table}'[{0}])))",
        "AVERAGEX(DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH), CALCULATE(SUM(Sales[Sales])))",
        0.68,
        ["requires marked date table", "window unit is a date grain"],
        ["windows over non-date axes"],
    ),
]
