"""Structural conversion-rule seeds (beyond 1:1 function mappings).

These encode the Section 6 realism constraints explicitly:
* nested LODs / table-calc-on-table-calc capped at ASSISTED;
* Qlik alternate states are MANUAL (bookmark / field-parameter redesign);
* Spotfire OVER with custom hierarchies is ASSISTED with mandatory review.

Tuple shape mirrors ConversionRule:
(rule_id, source_tool, source_pattern, source_example, dax_template,
 dax_example, confidence, preconditions, known_failure_modes)
"""

PATTERN_RULES: list[tuple] = [
    # ---------------- Tableau LOD ----------------
    (
        "tab-lod-fixed",
        "tableau",
        r"ast:lod-fixed",
        "{ FIXED [Customer] : SUM([Sales]) }",
        "CALCULATE({expr}, ALLEXCEPT({table}, {dims}))",
        "CALCULATE(SUM(Sales[Sales]), ALLEXCEPT(Sales, Sales[Customer]))",
        0.82,
        ["dimension columns resolve to a single table"],
        ["row-context usage differs from filter-context", "FIXED ignores some filters that ALLEXCEPT keeps"],
    ),
    (
        "tab-lod-fixed-nodim",
        "tableau",
        r"ast:lod-fixed-empty",
        "{ FIXED : SUM([Sales]) }",
        "CALCULATE({expr}, REMOVEFILTERS())",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS())",
        0.88,
        [],
        ["context filters in Tableau still apply to FIXED"],
    ),
    (
        "tab-lod-include",
        "tableau",
        r"ast:lod-include",
        "{ INCLUDE [Region] : AVG([Sales]) }",
        "AVERAGEX(VALUES({dim}), CALCULATE({expr}))",
        "AVERAGEX(VALUES(Sales[Region]), CALCULATE(SUM(Sales[Sales])))",
        0.72,
        ["outer aggregation re-applied by the visual"],
        ["double-aggregation mismatch when the outer agg differs from the visual's"],
    ),
    (
        "tab-lod-exclude",
        "tableau",
        r"ast:lod-exclude",
        "{ EXCLUDE [Month] : SUM([Sales]) }",
        "CALCULATE({expr}, REMOVEFILTERS({dims}))",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS(Sales[Month]))",
        0.78,
        [],
        ["EXCLUDE interacts with table-calc filters differently"],
    ),
    (
        "tab-lod-nested",
        "tableau",
        r"ast:lod-nested",
        "{ FIXED [A] : SUM({ INCLUDE [B] : MAX([X]) }) }",
        None,
        "-- nested LOD: composed CALCULATE/iterator chain, mandatory review",
        0.62,
        ["manual review of filter-context interaction"],
        ["nested context transitions rarely match 1:1", "performance of nested iterators"],
    ),
    (
        "tab-tc-on-tc",
        "tableau",
        r"ast:tablecalc-nested",
        "WINDOW_SUM(RUNNING_SUM(SUM([Sales])))",
        None,
        "-- table-calc-on-table-calc: composed WINDOW chain, mandatory review",
        0.60,
        ["explicit ORDERBY axis"],
        ["addressing/partitioning has no DAX analogue"],
    ),
    (
        "tab-pct-of-total",
        "tableau",
        r"(?i)SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*/\s*TOTAL\s*\(\s*SUM\s*\(\s*\[\1\]\s*\)\s*\)",
        "SUM([Sales]) / TOTAL(SUM([Sales]))",
        "DIVIDE(SUM('{table}'[{0}]), CALCULATE(SUM('{table}'[{0}]), ALLSELECTED()))",
        "DIVIDE(SUM(Sales[Sales]), CALCULATE(SUM(Sales[Sales]), ALLSELECTED()))",
        0.85,
        [],
        ["ALLSELECTED scope vs Tableau 'table (across)' scope"],
    ),
    # ---------------- Qlik set analysis ----------------
    (
        "qlik-set-field-value",
        "qlikview",
        r"ast:set-field-eq",
        "Sum({<Year={2024}>} Sales)",
        "CALCULATE(SUM({col}), {field} = {value})",
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = 2024)",
        0.85,
        [],
        ["search strings and wildcards in the element set"],
    ),
    (
        "qlik-set-exclude",
        "qlikview",
        r"ast:set-field-exclude",
        "Sum({<Region-={'EU'}>} Sales)",
        "CALCULATE(SUM({col}), {field} <> {value})",
        'CALCULATE(SUM(Sales[Sales]), Sales[Region] <> "EU")',
        0.82,
        [],
        ["multi-value exclusion needs NOT...IN pattern"],
    ),
    (
        "qlik-set-clear-field",
        "qlikview",
        r"ast:set-field-clear",
        "Sum({<Year=>} Sales)",
        "CALCULATE(SUM({col}), REMOVEFILTERS({field}))",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS(Sales[Year]))",
        0.88,
        [],
        [],
    ),
    (
        "qlik-set-all",
        "qlikview",
        r"ast:set-ignore-all",
        "Sum({1} Sales)",
        "CALCULATE(SUM({col}), REMOVEFILTERS())",
        "CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS())",
        0.88,
        [],
        ["{1} ignores selections but respects nothing else; ALL vs ALLSELECTED choice"],
    ),
    (
        "qlik-set-dollar-expansion",
        "qlikview",
        r"ast:set-dollar",
        "Sum({<Year={$(vMaxYear)}>} Sales)",
        None,
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = [Max Year Value])  -- via measure/what-if",
        0.65,
        ["variable resolves to a measure or what-if parameter"],
        ["dollar expansions executing arbitrary expressions"],
    ),
    (
        "qlik-set-element-func",
        "qlikview",
        r"ast:set-pe-func",
        "Sum({<Customer=P({<Year={2024}>} Customer)>} Sales)",
        None,
        "CALCULATE(SUM(Sales[Sales]), CALCULATETABLE(VALUES(Sales[Customer]), Sales[Year]=2024))",
        0.62,
        ["review filter direction"],
        ["E() exclusion sets invert subtly"],
    ),
    (
        "qlik-alternate-state",
        "qlikview",
        r"ast:set-alternate-state",
        "Sum({State1<Year={2024}>} Sales)",
        None,
        "-- no DAX equivalent: redesign with bookmarks / field parameters / calc groups",
        0.30,
        [],
        ["alternate states have no Power BI filter-context analogue"],
    ),
    (
        "qlik-aggr",
        "qlikview",
        r"ast:aggr",
        "Avg(Aggr(Sum(Sales), Customer))",
        'AVERAGEX(SUMMARIZE({table}, {dims}, "@v", {expr}), [@v])',
        'AVERAGEX(SUMMARIZE(Sales, Sales[Customer], "@v", CALCULATE(SUM(Sales[Sales]))), [@v])',
        0.72,
        ["Aggr dimensions resolve to model columns"],
        ["nested Aggr", "Aggr with sort-weight arguments"],
    ),
    (
        "qlik-total-qualifier",
        "qlikview",
        r"(?i)\b(Sum|Avg|Min|Max|Count)\s*\(\s*TOTAL\b",
        "Sum(TOTAL Sales)",
        "CALCULATE({agg}({col}), ALLSELECTED())",
        "CALCULATE(SUM(Sales[Sales]), ALLSELECTED())",
        0.82,
        [],
        ["TOTAL <dims> qualified form needs ALLEXCEPT instead"],
    ),
    (
        "qlik-interrecord-chart",
        "qlikview",
        r"(?i)\b(Above|Below)\s*\(",
        "Sum(Sales) / Above(Sum(Sales))",
        None,
        "DIVIDE([Sales], CALCULATE([Sales], OFFSET(-1, ORDERBY('Date'[Month]))))",
        0.60,
        ["explicit ORDERBY axis"],
        ["visual sort order vs ORDERBY mismatch"],
    ),
    # ---------------- Qlik Sense specifics ----------------
    (
        "qs-master-measure",
        "qliksense",
        r"ast:master-measure",
        "Master measure 'Total Sales'",
        "{expr}",
        "Total Sales = SUM(Sales[Sales])  -- becomes a model measure",
        0.90,
        [],
        [],
    ),
    (
        "qs-variable-expansion",
        "qliksense",
        r"\$\(\w+\)",
        "$(vDiscount) * Sum(Sales)",
        None,
        "-- variable: map to what-if parameter or measure; review each expansion",
        0.60,
        ["variable is a constant or simple expression"],
        ["variables containing expression fragments (token splicing)"],
    ),
    # ---------------- Spotfire ----------------
    (
        "spot-over-all",
        "spotfire",
        r"ast:over-all",
        "Sum([Sales]) OVER (All([Axis.X]))",
        "CALCULATE({expr}, ALLSELECTED({dim}))",
        "CALCULATE(SUM(Sales[Sales]), ALLSELECTED(Sales[Region]))",
        0.80,
        [],
        ["Axis.X binding must be resolved to a model column"],
    ),
    (
        "spot-over-allprevious",
        "spotfire",
        r"ast:over-allprevious",
        "Sum([Sales]) OVER (AllPrevious([Axis.X]))",
        "CALCULATE({expr}, FILTER(ALLSELECTED({dim}), {dim} <= MAX({dim})))",
        "CALCULATE(SUM(Sales[Sales]), FILTER(ALLSELECTED('Date'[Month]), 'Date'[Month] <= MAX('Date'[Month])))",
        0.75,
        ["axis column is ordered"],
        ["categorical (non-ordered) axes"],
    ),
    (
        "spot-over-intersect-custom",
        "spotfire",
        r"ast:over-intersect-hierarchy",
        "Sum([Sales]) OVER (Intersect([Hier1], AllPrevious([Axis.X])))",
        None,
        "-- OVER with custom hierarchies: ASSISTED, mandatory review",
        0.60,
        ["hierarchy levels exist as model columns"],
        ["custom hierarchy slicing has no direct filter-context analogue"],
    ),
    (
        "spot-then",
        "spotfire",
        r"(?i)\bTHEN\b",
        "Sum([Sales]) THEN [Value] / Max([Value]) OVER (All([Axis.X]))",
        None,
        "-- THEN post-aggregation: chain via VARs in one measure; review",
        0.60,
        [],
        ["multi-stage THEN chains"],
    ),
    (
        "spot-case",
        "spotfire",
        r"(?i)\bCASE\s+WHEN\b",
        "CASE WHEN [Sales] > 100 THEN 'High' ELSE 'Low' END",
        "SWITCH(TRUE(), {cond1}, {val1}, {default})",
        'SWITCH(TRUE(), Sales[Sales] > 100, "High", "Low")',
        0.88,
        [],
        [],
    ),
    # ---------------- cross-cutting time intelligence ----------------
    (
        "xx-ytd",
        "tableau",
        r"(?i)RUNNING_SUM\s*\(\s*SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*\)",
        "RUNNING_SUM(SUM([Sales])) partitioned by year",
        "TOTALYTD(SUM('{table}'[{0}]), 'Date'[Date])",
        "TOTALYTD(SUM(Sales[Sales]), 'Date'[Date])",
        0.70,
        ["requires marked date table", "partition is calendar year"],
        ["running totals not aligned to calendar periods"],
    ),
    (
        "xx-moving-avg",
        "tableau",
        r"(?i)WINDOW_AVG\s*\(\s*SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*,\s*-(\d+)\s*,\s*0\s*\)",
        "WINDOW_AVG(SUM([Sales]), -2, 0)",
        "AVERAGEX(DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -{1}, MONTH), CALCULATE(SUM('{table}'[{0}])))",
        "AVERAGEX(DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH), CALCULATE(SUM(Sales[Sales])))",
        0.68,
        ["requires marked date table", "window unit is a date grain"],
        ["windows over non-date axes"],
    ),
]

# -- expansion wave 2: idiom-level patterns seen in real estates.
PATTERN_RULES += [
    (
        "qlik-pct-of-total",
        "qlikview",
        r"(?i)Sum\s*\(\s*(\w+)\s*\)\s*/\s*Sum\s*\(\s*TOTAL\s+\1\s*\)",
        "Sum(Sales) / Sum(TOTAL Sales)",
        "DIVIDE(SUM({col}), CALCULATE(SUM({col}), ALLSELECTED()))",
        "DIVIDE(SUM(Sales[Sales]), CALCULATE(SUM(Sales[Sales]), ALLSELECTED()))",
        0.85,
        [],
        ["TOTAL <dims> qualified form needs ALLEXCEPT"],
    ),
    (
        "qlik-sum-if",
        "qlikview",
        r"(?i)Sum\s*\(\s*If\s*\(",
        "Sum(If(Status='Open', Amount))",
        "CALCULATE(SUM({col}), {condition})",
        'CALCULATE(SUM(Sales[Amount]), Sales[Status] = "Open")',
        0.75,
        ["condition references model columns only"],
        ["row-level conditions mixing aggregates need FILTER table form"],
    ),
    (
        "qlik-rangesum-above",
        "qlikview",
        r"(?i)RangeSum\s*\(\s*Above\s*\(",
        "RangeSum(Above(Sum(Sales), 0, RowNo()))",
        None,
        "SUMX(WINDOW(1, ABS, 0, REL, ORDERBY([Month])), [Sales])",
        0.60,
        ["explicit ORDERBY axis"],
        ["visual sort order dependence", "pivoted dimensions break the window"],
    ),
    (
        "qlik-set-numeric-range",
        "qlikview",
        r"ast:set-range",
        'Sum({<Amount={">=100<200"}>} Sales)',
        None,
        "CALCULATE(SUM(Sales[Sales]), Sales[Amount] >= 100 && Sales[Amount] < 200)",
        0.58,
        [],
        ["search-string range parsing is per-instance manual work"],
    ),
    (
        "qlik-set-wildcard",
        "qlikview",
        r"ast:set-wildcard",
        'Sum({<Product={"A*"}>} Sales)',
        None,
        "CALCULATE(SUM(Sales[Sales]), FILTER(VALUES(Sales[Product]), " 'LEFT(Sales[Product], 1) = "A"))',
        0.55,
        [],
        ["wildcard semantics differ from LEFT/CONTAINSSTRING rewrites"],
    ),
    (
        "qs-drilldown-hierarchy",
        "qliksense",
        r"ast:drilldown-dim",
        "Drill-down master dimension (Region > Country > City)",
        "{hierarchy}",
        "Model hierarchy Region > Country > City on the dimension table",
        0.85,
        ["levels exist as model columns"],
        [],
    ),
    (
        "tab-iif-zero-guard",
        "tableau",
        r"(?i)IIF\s*\(\s*\[?\w+\]?\s*=\s*0\s*,\s*NULL\s*,",
        "IIF([Denominator] = 0, NULL, [Numerator] / [Denominator])",
        "DIVIDE({numerator}, {denominator})",
        "DIVIDE(SUM(Sales[Profit]), SUM(Sales[Sales]))",
        0.88,
        [],
        [],
    ),
    (
        "tab-yoy-lookup",
        "tableau",
        r"(?i)LOOKUP\s*\(\s*ZN\s*\(\s*SUM",
        "(ZN(SUM([Sales])) - LOOKUP(ZN(SUM([Sales])), -1)) / ABS(LOOKUP(ZN(SUM([Sales])), -1))",
        None,
        "VAR _prev = CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date])) "
        "RETURN DIVIDE([Sales] - _prev, ABS(_prev))",
        0.62,
        ["requires marked date table", "offset axis is a calendar period"],
        ["LOOKUP offsets over non-date axes"],
    ),
    (
        "tab-fixed-max-date",
        "tableau",
        r"(?i)\{\s*FIXED\s*:\s*MAX\s*\(\s*\[[^\]]+\]\s*\)\s*\}",
        "{ FIXED : MAX([Order Date]) }",
        "CALCULATE(MAX({col}), REMOVEFILTERS())",
        "CALCULATE(MAX(Sales[Order Date]), REMOVEFILTERS())",
        0.85,
        [],
        ["context filters still apply to Tableau FIXED"],
    ),
    (
        "tab-countd-fixed",
        "tableau",
        r"(?i)COUNTD\s*\(\s*\[[^\]]+\]\s*\)",
        "COUNTD([Customer])",
        "DISTINCTCOUNT({col})",
        "DISTINCTCOUNT(Sales[Customer])",
        0.92,
        [],
        ["COUNTD across blended sources has no direct equivalent"],
    ),
    (
        "spot-pct-of-total",
        "spotfire",
        r"(?i)Sum\s*\(\s*\[([^\]]+)\]\s*\)\s*/\s*Sum\s*\(\s*\[\1\]\s*\)\s*OVER\s*\(\s*All\s*\(",
        "Sum([Sales]) / Sum([Sales]) OVER (All([Axis.X]))",
        "DIVIDE(SUM({col}), CALCULATE(SUM({col}), ALLSELECTED({dim})))",
        "DIVIDE(SUM(Sales[Sales]), CALCULATE(SUM(Sales[Sales]), ALLSELECTED(Sales[Region])))",
        0.82,
        ["Axis.X resolves to a model column"],
        [],
    ),
    (
        "spot-moving-avg-lastperiods",
        "spotfire",
        r"(?i)OVER\s*\(\s*LastPeriods\s*\(",
        "Avg([Sales]) OVER (LastPeriods(3, [Axis.X]))",
        None,
        "AVERAGEX(DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH), [Sales])",
        0.65,
        ["requires marked date table", "axis is a date grain"],
        ["LastPeriods over categorical axes"],
    ),
    (
        "spot-over-parent-share",
        "spotfire",
        r"(?i)OVER\s*\(\s*Parent\s*\(",
        "Sum([Sales]) / Sum([Sales]) OVER (Parent([Axis.X]))",
        None,
        "DIVIDE(SUM(Sales[Sales]), CALCULATE(SUM(Sales[Sales]), REMOVEFILTERS('Date'[Month])))",
        0.68,
        ["hierarchy levels exist as model columns"],
        [],
    ),
    (
        "xx-incremental-refresh",
        "tableau",
        r"ast:extract-incremental",
        "Extract with incremental refresh on [Order Date]",
        "{policy}",
        "Incremental refresh policy: RangeStart/RangeEnd parameters on Order Date",
        0.80,
        ["date column is immutable-append"],
        ["late-arriving updates"],
    ),
    (
        "xx-qvd-medallion",
        "qlikview",
        r"ast:qvd-layer",
        "Extract QVD -> Transform QVD -> app load chain",
        "{pipeline}",
        "Lakehouse medallion: bronze (raw landing) -> silver (cleansed) -> gold "
        "(star schema) with Dataflow Gen2 per layer",
        0.70,
        [],
        ["QVD optimized-load tricks have no M analogue"],
    ),
]

PATTERN_RULES += [
    (
        "tab-window-sum-full",
        "tableau",
        r"(?i)WINDOW_SUM\s*\(\s*SUM\s*\(\s*\[([^\]]+)\]\s*\)\s*\)",
        "WINDOW_SUM(SUM([Sales]))",
        "CALCULATE(SUM('{table}'[{0}]), ALLSELECTED())",
        "CALCULATE(SUM(Sales[Sales]), ALLSELECTED())",
        0.78,
        [],
        ["non-default compute-using changes the window scope"],
    ),
    (
        "tab-dual-axis",
        "tableau",
        r"ast:dual-axis",
        "Dual-axis worksheet (measure on each axis)",
        "{combo}",
        "Line and stacked column combo chart with secondary y-axis",
        0.75,
        ["both marks are line/bar compatible"],
        ["dual maps and shape/scatter dual axes need redesign"],
    ),
    (
        "qlik-set-year-max",
        "qlikview",
        r"(?i)\{\s*<\s*\w+\s*=\s*\{\s*\$\(\s*=\s*Max\s*\(",
        "Sum({<Year={$(=Max(Year))}>} Sales)",
        None,
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = CALCULATE(MAX(Sales[Year]), ALLSELECTED()))",
        0.62,
        [],
        ["inner Max scope vs selection state differs"],
    ),
    (
        "qs-alternate-state",
        "qliksense",
        r"ast:set-alternate-state",
        "Sum({AltState<Year={2024}>} Sales)",
        None,
        "-- no DAX equivalent: redesign with bookmarks / field parameters",
        0.30,
        [],
        ["alternate states have no Power BI filter-context analogue"],
    ),
    (
        "spot-uniquecount-over-all",
        "spotfire",
        r"(?i)UniqueCount\s*\(\s*\[([^\]]+)\]\s*\)\s*OVER\s*\(\s*All\s*\(",
        "UniqueCount([Customer]) OVER (All([Axis.X]))",
        "CALCULATE(DISTINCTCOUNT({col}), ALLSELECTED())",
        "CALCULATE(DISTINCTCOUNT(Sales[Customer]), ALLSELECTED())",
        0.80,
        [],
        [],
    ),
    (
        "xx-subscription-cadence",
        "tableau",
        r"ast:subscription",
        "Daily 08:00 email subscription to dashboard",
        "{subscription}",
        "Power BI email subscription (per user) or Power Automate scheduled "
        "export for shared distribution",
        0.70,
        [],
        ["attachment formats and burst distribution differ"],
    ),
    (
        "xx-alert-threshold",
        "tableau",
        r"ast:data-alert",
        "Data-driven alert when SUM(Sales) < threshold",
        "{alert}",
        "Power BI alert on card/KPI visual, or Power Automate flow over a DAX query",
        0.65,
        [],
        ["multi-condition alerts require the Power Automate path"],
    ),
    (
        "qlik-intervalmatch-range-join",
        "qlikview",
        r"(?i)\bIntervalMatch\b",
        "IntervalMatch(Date) LOAD Start, End RESIDENT Periods;",
        None,
        "M range join: expand periods, Table.SelectRows(start <= x and x <= end); "
        "or DAX: FILTER('Periods', 'Fact'[Date] >= [Start] && 'Fact'[Date] <= [End])",
        0.55,
        [],
        ["row-explosion performance on large interval tables"],
    ),
]
