"""Qlik (QlikView + Qlik Sense shared expression language) function
reference with DAX mappings.

Tuple shape: (name, signature, category, dax_equivalent, dax_template, confidence, notes)

Set-analysis and Aggr() are handled structurally by the Qlik AST
translator; entries here cover the function-name surface. Inter-record
functions (Peek/Previous/RowNo...) belong to the load script and map to
Power Query, not DAX — they carry M guidance in notes.
"""

QLIK_FUNCTIONS: list[tuple] = [
    # ---- basic aggregation ----
    ("Sum", "Sum([expr])", "aggregate", "SUM", "SUM({0})", 0.97, ""),
    ("Avg", "Avg([expr])", "aggregate", "AVERAGE", "AVERAGE({0})", 0.95, ""),
    ("Min", "Min([expr])", "aggregate", "MIN", "MIN({0})", 0.95, ""),
    ("Max", "Max([expr])", "aggregate", "MAX", "MAX({0})", 0.95, ""),
    (
        "Count",
        "Count([expr])",
        "aggregate",
        "COUNT",
        "COUNT({0})",
        0.92,
        "Count(DISTINCT x) maps to DISTINCTCOUNT",
    ),
    (
        "Only",
        "Only([expr])",
        "aggregate",
        "SELECTEDVALUE",
        "SELECTEDVALUE({0})",
        0.85,
        "Both return blank/null when more than one value exists",
    ),
    ("Mode", "Mode([expr])", "aggregate", None, None, 0.5, "Compose: TOPN(1, SUMMARIZE...) by count; review"),
    ("Median", "Median([expr])", "aggregate", "MEDIAN", "MEDIAN({0})", 0.95, ""),
    (
        "Fractile",
        "Fractile([expr], fraction)",
        "aggregate",
        "PERCENTILE.INC",
        "PERCENTILE.INC({0}, {1})",
        0.92,
        "",
    ),
    ("Stdev", "Stdev([expr])", "aggregate", "STDEV.S", "STDEV.S({0})", 0.95, ""),
    (
        "Skew",
        "Skew([expr])",
        "aggregate",
        None,
        None,
        0.4,
        "No DAX skewness; compose iterator math or push upstream",
    ),
    (
        "Kurtosis",
        "Kurtosis([expr])",
        "aggregate",
        None,
        None,
        0.4,
        "No DAX kurtosis; compose iterator math or push upstream",
    ),
    (
        "NumericCount",
        "NumericCount([expr])",
        "aggregate",
        None,
        "COUNTX(FILTER(VALUES({0}), ISNUMBER({0})), {0})",
        0.70,
        "",
    ),
    (
        "TextCount",
        "TextCount([expr])",
        "aggregate",
        None,
        "COUNTX(FILTER(VALUES({0}), NOT ISNUMBER({0})), {0})",
        0.65,
        "",
    ),
    (
        "MissingCount",
        "MissingCount([expr])",
        "aggregate",
        None,
        "COUNTROWS(FILTER(ALLSELECTED(), ISBLANK({0})))",
        0.60,
        "Null semantics differ; review",
    ),
    (
        "NullCount",
        "NullCount([expr])",
        "aggregate",
        None,
        "COUNTROWS(FILTER(ALLSELECTED(), ISBLANK({0})))",
        0.60,
        "Null semantics differ; review",
    ),
    (
        "FirstSortedValue",
        "FirstSortedValue([value], [sort-weight])",
        "aggregate",
        None,
        "MAXX(TOPN(1, ALLSELECTED(), {1}, ASC), {0})",
        0.65,
        "Verify tie handling",
    ),
    (
        "Concat",
        "Concat([expr], delimiter)",
        "aggregate",
        "CONCATENATEX",
        "CONCATENATEX(VALUES({0}), {0}, {1})",
        0.88,
        "Ordering argument may be needed",
    ),
    ("MinString", "MinString([expr])", "aggregate", None, "MINX(VALUES({0}), {0})", 0.85, ""),
    ("MaxString", "MaxString([expr])", "aggregate", None, "MAXX(VALUES({0}), {0})", 0.85, ""),
    # ---- advanced aggregation ----
    (
        "Aggr",
        "Aggr(expr, dim1, ...)",
        "advanced",
        None,
        None,
        0.65,
        "Structural translation: iterator over SUMMARIZE/VALUES of the Aggr dimensions; "
        "nested Aggr or sort-weighted Aggr is MANUAL",
    ),
    # ---- range (row-scalar) ----
    (
        "RangeSum",
        "RangeSum(a, b, ...)",
        "range",
        None,
        "({0})",
        0.80,
        "Null-safe addition: emit COALESCE(x,0) + ... chain",
    ),
    ("RangeAvg", "RangeAvg(a, b, ...)", "range", None, None, 0.60, "Compose with COALESCE chain"),
    (
        "RangeMin",
        "RangeMin(a, b, ...)",
        "range",
        "MIN",
        "MIN({0}, {1})",
        0.80,
        "DAX MIN takes 2 args; chain for more",
    ),
    ("RangeMax", "RangeMax(a, b, ...)", "range", "MAX", "MAX({0}, {1})", 0.80, "Chain for >2 args"),
    # ---- conditional ----
    ("If", "If(condition, then, else)", "logical", "IF", "IF({0}, {1}, {2})", 0.95, ""),
    (
        "Match",
        "Match(expr, v1, v2, ...)",
        "logical",
        "SWITCH",
        None,
        0.85,
        "Match returns position int; SWITCH chain emitted structurally",
    ),
    (
        "WildMatch",
        "WildMatch(expr, pattern1, ...)",
        "logical",
        None,
        None,
        0.5,
        "Wildcards map to SEARCH/CONTAINSSTRING compositions; review each pattern",
    ),
    ("Pick", "Pick(n, v1, v2, ...)", "logical", "SWITCH", "SWITCH({0}, 1, {1}, 2, {2})", 0.85, ""),
    ("Alt", "Alt(expr1, expr2, ...)", "logical", "COALESCE", "COALESCE({0}, {1})", 0.92, ""),
    ("Coalesce", "Coalesce(expr1, expr2, ...)", "logical", "COALESCE", "COALESCE({0}, {1})", 0.95, ""),
    ("IsNull", "IsNull(expr)", "logical", "ISBLANK", "ISBLANK({0})", 0.92, ""),
    ("Null", "Null()", "logical", "BLANK", "BLANK()", 0.95, ""),
    (
        "Class",
        "Class(expr, interval)",
        "logical",
        None,
        "INT(DIVIDE({0}, {1})) * {1}",
        0.70,
        "Binning; consider Power BI grouping/bins instead",
    ),
    (
        "Dual",
        "Dual(text, number)",
        "logical",
        None,
        None,
        0.3,
        "No dual values in DAX; model as separate sort-by column",
    ),
    # ---- numeric ----
    ("Floor", "Floor(x, [step])", "number", "FLOOR", "FLOOR({0}, {1})", 0.92, "Default step 1"),
    ("Ceil", "Ceil(x, [step])", "number", "CEILING", "CEILING({0}, {1})", 0.92, "Default step 1"),
    (
        "Round",
        "Round(x, [step])",
        "number",
        "MROUND",
        "MROUND({0}, {1})",
        0.88,
        "Qlik rounds to step multiples; plain ROUND when step is power of 10",
    ),
    ("Fabs", "Fabs(x)", "number", "ABS", "ABS({0})", 0.97, ""),
    ("Sqrt", "Sqrt(x)", "number", "SQRT", "SQRT({0})", 0.97, ""),
    ("Sqr", "Sqr(x)", "number", None, "({0}) ^ 2", 0.95, ""),
    ("Exp", "Exp(x)", "number", "EXP", "EXP({0})", 0.97, ""),
    ("Log", "Log(x)", "number", "LN", "LN({0})", 0.95, "Qlik Log is natural log"),
    ("Log10", "Log10(x)", "number", "LOG10", "LOG10({0})", 0.97, ""),
    ("Pow", "Pow(x, y)", "number", "POWER", "POWER({0}, {1})", 0.97, ""),
    ("Mod", "Mod(x, y)", "number", "MOD", "MOD({0}, {1})", 0.95, ""),
    ("Sign", "Sign(x)", "number", "SIGN", "SIGN({0})", 0.97, ""),
    # ---- string ----
    ("Left", "Left(s, n)", "string", "LEFT", "LEFT({0}, {1})", 0.97, ""),
    ("Right", "Right(s, n)", "string", "RIGHT", "RIGHT({0}, {1})", 0.97, ""),
    ("Mid", "Mid(s, start, [count])", "string", "MID", "MID({0}, {1}, {2})", 0.95, ""),
    ("Len", "Len(s)", "string", "LEN", "LEN({0})", 0.97, ""),
    ("Upper", "Upper(s)", "string", "UPPER", "UPPER({0})", 0.97, ""),
    ("Lower", "Lower(s)", "string", "LOWER", "LOWER({0})", 0.97, ""),
    ("Capitalize", "Capitalize(s)", "string", None, None, 0.45, "No DAX PROPER; Text.Proper in Power Query"),
    ("Trim", "Trim(s)", "string", "TRIM", "TRIM({0})", 0.95, ""),
    ("LTrim", "LTrim(s)", "string", None, None, 0.45, "Power Query Text.TrimStart"),
    ("RTrim", "RTrim(s)", "string", None, None, 0.45, "Power Query Text.TrimEnd"),
    ("Replace", "Replace(s, from, to)", "string", "SUBSTITUTE", "SUBSTITUTE({0}, {1}, {2})", 0.95, ""),
    (
        "SubField",
        "SubField(s, delim, [n])",
        "string",
        "PATHITEM",
        'PATHITEM(SUBSTITUTE({0}, {1}, "|"), {2})',
        0.70,
        "Prefer Power Query Text.Split at load time",
    ),
    (
        "Index",
        "Index(s, substring, [n])",
        "string",
        "SEARCH",
        "SEARCH({1}, {0}, 1, 0)",
        0.88,
        "Argument order swaps; nth occurrence unsupported",
    ),
    ("FindOneOf", "FindOneOf(s, charset)", "string", None, None, 0.4, "Power Query equivalent"),
    (
        "PurgeChar",
        "PurgeChar(s, chars)",
        "string",
        None,
        None,
        0.45,
        "Chain SUBSTITUTE per char or Power Query Text.Remove",
    ),
    ("KeepChar", "KeepChar(s, chars)", "string", None, None, 0.4, "Power Query Text.Select"),
    ("Chr", "Chr(n)", "string", "UNICHAR", "UNICHAR({0})", 0.95, ""),
    ("Ord", "Ord(s)", "string", "UNICODE", "UNICODE({0})", 0.95, ""),
    ("Repeat", "Repeat(s, n)", "string", "REPT", "REPT({0}, {1})", 0.95, ""),
    (
        "Num",
        "Num(expr, [format])",
        "format",
        "FORMAT",
        "FORMAT({0}, {1})",
        0.80,
        "Format codes differ; emitter maps common Qlik format patterns",
    ),
    ("Text", "Text(expr)", "format", "FORMAT", 'FORMAT({0}, "General")', 0.88, ""),
    ("Money", "Money(expr, [format])", "format", "FORMAT", 'FORMAT({0}, "Currency")', 0.85, ""),
    # ---- date & time ----
    ("Year", "Year(date)", "date", "YEAR", "YEAR({0})", 0.97, ""),
    (
        "Month",
        "Month(date)",
        "date",
        "MONTH",
        "MONTH({0})",
        0.92,
        "Qlik Month returns a dual (name+number); DAX returns number — pair with FORMAT for labels",
    ),
    ("Day", "Day(date)", "date", "DAY", "DAY({0})", 0.97, ""),
    ("Hour", "Hour(ts)", "date", "HOUR", "HOUR({0})", 0.97, ""),
    ("Minute", "Minute(ts)", "date", "MINUTE", "MINUTE({0})", 0.97, ""),
    ("Second", "Second(ts)", "date", "SECOND", "SECOND({0})", 0.97, ""),
    ("Week", "Week(date)", "date", "WEEKNUM", "WEEKNUM({0})", 0.88, "ISO week conventions differ"),
    (
        "WeekDay",
        "WeekDay(date)",
        "date",
        "WEEKDAY",
        "WEEKDAY({0})",
        0.88,
        "Qlik returns dual name; map numbering convention",
    ),
    ("WeekYear", "WeekYear(date)", "date", None, None, 0.5, "Compose ISO week-year logic"),
    ("Today", "Today([timer_mode])", "date", "TODAY", "TODAY()", 0.97, ""),
    ("Now", "Now([timer_mode])", "date", "NOW", "NOW()", 0.97, ""),
    ("MakeDate", "MakeDate(y, [m], [d])", "date", "DATE", "DATE({0}, {1}, {2})", 0.95, ""),
    ("AddMonths", "AddMonths(date, n)", "date", "EDATE", "EDATE({0}, {1})", 0.95, ""),
    ("AddYears", "AddYears(date, n)", "date", "EDATE", "EDATE({0}, 12 * {1})", 0.92, ""),
    (
        "MonthStart",
        "MonthStart(date)",
        "date",
        None,
        "DATE(YEAR({0}), MONTH({0}), 1)",
        0.92,
        "STARTOFMONTH only works on date-table columns",
    ),
    ("MonthEnd", "MonthEnd(date)", "date", "EOMONTH", "EOMONTH({0}, 0)", 0.92, ""),
    ("YearStart", "YearStart(date)", "date", None, "DATE(YEAR({0}), 1, 1)", 0.92, ""),
    ("YearEnd", "YearEnd(date)", "date", None, "DATE(YEAR({0}), 12, 31)", 0.92, ""),
    (
        "QuarterStart",
        "QuarterStart(date)",
        "date",
        None,
        "DATE(YEAR({0}), 3 * QUARTER({0}) - 2, 1)",
        0.88,
        "",
    ),
    (
        "QuarterEnd",
        "QuarterEnd(date)",
        "date",
        None,
        "EOMONTH(DATE(YEAR({0}), 3 * QUARTER({0}), 1), 0)",
        0.88,
        "",
    ),
    (
        "WeekStart",
        "WeekStart(date)",
        "date",
        None,
        "{0} - WEEKDAY({0}, 2) + 1",
        0.80,
        "Week-start convention (Mon/Sun) must match",
    ),
    ("WeekEnd", "WeekEnd(date)", "date", None, "{0} + 7 - WEEKDAY({0}, 2)", 0.80, ""),
    (
        "InYear",
        "InYear(date, base, shift)",
        "date",
        None,
        None,
        0.5,
        "Set-analysis style period test; usually replaced by date-table filtering",
    ),
    ("InMonth", "InMonth(date, base, shift)", "date", None, None, 0.5, "As InYear"),
    ("InQuarter", "InQuarter(date, base, shift)", "date", None, None, 0.5, "As InYear"),
    (
        "YearToDate",
        "YearToDate(date, ...)",
        "date",
        None,
        None,
        0.6,
        "Replace with TOTALYTD measure pattern (requires marked date table)",
    ),
    (
        "NetWorkDays",
        "NetWorkDays(start, end, [holidays])",
        "date",
        "NETWORKDAYS",
        "NETWORKDAYS({0}, {1})",
        0.90,
        "",
    ),
    ("Age", "Age(ts, date)", "date", None, None, 0.5, "Compose with DATEDIFF + birthday logic"),
    # ---- inter-record / counters (load-script only -> Power Query) ----
    (
        "Peek",
        "Peek(field, [row], [table])",
        "script",
        None,
        None,
        0.5,
        "Load-script function; M equivalent: indexed access on a buffered table or List.Generate",
    ),
    (
        "Previous",
        "Previous(expr)",
        "script",
        None,
        None,
        0.5,
        "Load-script function; M: shifted column join (Table.AddIndexColumn + merge on index-1)",
    ),
    ("RowNo", "RowNo()", "script", None, None, 0.6, "M: Table.AddIndexColumn"),
    ("RecNo", "RecNo()", "script", None, None, 0.6, "M: Table.AddIndexColumn on the raw source"),
    (
        "IterNo",
        "IterNo()",
        "script",
        None,
        None,
        0.3,
        "WHILE-loop loads have no direct M analogue; List.Generate redesign",
    ),
    (
        "Exists",
        "Exists(field, [expr])",
        "script",
        None,
        None,
        0.5,
        "M: inner join / List.Contains against previously loaded values",
    ),
    (
        "ApplyMap",
        "ApplyMap('map', expr, [default])",
        "script",
        None,
        None,
        0.7,
        "M: merge with the mapping table + default on no-match (Table.NestedJoin pattern)",
    ),
    ("FieldValue", "FieldValue(field, n)", "script", None, None, 0.4, "Model redesign"),
    ("FieldIndex", "FieldIndex(field, value)", "script", None, None, 0.4, "Model redesign"),
    # ---- chart inter-record (visual-relative) ----
    (
        "Above",
        "Above(expr, [offset])",
        "chart",
        "OFFSET",
        "CALCULATE({0}, OFFSET(-{1}, ORDERBY([Date])))",
        0.60,
        "Visual-relative reference; OFFSET needs explicit axis",
    ),
    (
        "Below",
        "Below(expr, [offset])",
        "chart",
        "OFFSET",
        "CALCULATE({0}, OFFSET({1}, ORDERBY([Date])))",
        0.60,
        "As Above",
    ),
    (
        "Before",
        "Before(expr, [offset])",
        "chart",
        None,
        None,
        0.3,
        "Pivot-column-relative; no DAX analogue — redesign",
    ),
    ("After", "After(expr, [offset])", "chart", None, None, 0.3, "As Before"),
    ("Top", "Top(expr)", "chart", None, None, 0.4, "Visual-relative; WINDOW/INDEX redesign"),
    ("Bottom", "Bottom(expr)", "chart", None, None, 0.4, "As Top"),
    ("First", "First(expr)", "chart", None, None, 0.4, "As Top"),
    ("Last", "Last(expr)", "chart", None, None, 0.4, "As Top"),
    ("RowNo_chart", "RowNo([TOTAL])", "chart", None, None, 0.5, "Chart RowNo -> RANKX/INDEX"),
    ("ColumnNo", "ColumnNo([TOTAL])", "chart", None, None, 0.3, "No analogue; redesign"),
    ("NoOfRows", "NoOfRows([TOTAL])", "chart", "COUNTROWS", "COUNTROWS(ALLSELECTED())", 0.65, ""),
    (
        "Rank",
        "Rank(expr, [mode], [fmt])",
        "chart",
        "RANKX",
        "RANKX(ALLSELECTED(), {0})",
        0.78,
        "Verify partitioning (TOTAL qualifier) and tie mode",
    ),
    ("HRank", "HRank(expr)", "chart", None, None, 0.3, "Horizontal pivot rank; redesign"),
    # ---- selection / UI state ----
    (
        "GetFieldSelections",
        "GetFieldSelections(field)",
        "ui",
        None,
        'CONCATENATEX(VALUES({0}), {0}, ", ")',
        0.65,
        "Selected-values display; semantics differ when nothing selected",
    ),
    (
        "GetSelectedCount",
        "GetSelectedCount(field)",
        "ui",
        None,
        "COUNTROWS(VALUES({0}))",
        0.60,
        "Counts filtered values, not explicit selections",
    ),
    (
        "GetCurrentSelections",
        "GetCurrentSelections()",
        "ui",
        None,
        None,
        0.3,
        "No DAX analogue for global selection string; use filter-pane visuals",
    ),
    (
        "GetObjectField",
        "GetObjectField([n])",
        "ui",
        None,
        None,
        0.2,
        "Cyclic dimensions -> field parameters redesign",
    ),
]

# -- expansion wave 2: trigonometry, counters, date/name duals, format-parse,
#    statistical ranges. Same tuple shape; unmapped entries (None/None) carry
#    fallback guidance in notes and create no conversion rule.
QLIK_FUNCTIONS += [
    # trigonometry / advanced math
    ("Cos", "Cos(x)", "number", "COS", "COS({0})", 0.98, ""),
    ("Sin", "Sin(x)", "number", "SIN", "SIN({0})", 0.98, ""),
    ("Tan", "Tan(x)", "number", "TAN", "TAN({0})", 0.98, ""),
    ("Acos", "Acos(x)", "number", "ACOS", "ACOS({0})", 0.98, ""),
    ("Asin", "Asin(x)", "number", "ASIN", "ASIN({0})", 0.98, ""),
    ("Atan", "Atan(x)", "number", "ATAN", "ATAN({0})", 0.98, ""),
    (
        "Atan2",
        "Atan2(y, x)",
        "number",
        "ATAN",
        "ATAN(DIVIDE({0}, {1}))",
        0.80,
        "Quadrant handling differs from two-argument arctangent; review",
    ),
    ("Cosh", "Cosh(x)", "number", "COSH", "COSH({0})", 0.97, ""),
    ("Sinh", "Sinh(x)", "number", "SINH", "SINH({0})", 0.97, ""),
    ("Tanh", "Tanh(x)", "number", "TANH", "TANH({0})", 0.97, ""),
    ("Div", "Div(x, y)", "number", "QUOTIENT", "QUOTIENT({0}, {1})", 0.95, ""),
    (
        "Fmod",
        "Fmod(x, y)",
        "number",
        "MOD",
        "MOD({0}, {1})",
        0.90,
        "Sign convention differs for negative operands; review",
    ),
    ("Frac", "Frac(x)", "number", None, "{0} - TRUNC({0})", 0.92, ""),
    ("Even", "Even(n)", "number", "ISEVEN", "ISEVEN({0})", 0.95, ""),
    ("Odd", "Odd(n)", "number", "ISODD", "ISODD({0})", 0.95, ""),
    ("Fact", "Fact(n)", "number", "FACT", "FACT({0})", 0.97, ""),
    ("Combin", "Combin(n, k)", "number", "COMBIN", "COMBIN({0}, {1})", 0.95, ""),
    ("Permut", "Permut(n, k)", "number", "PERMUT", "PERMUT({0}, {1})", 0.95, ""),
    (
        "Rand",
        "Rand()",
        "number",
        "RAND",
        "RAND()",
        0.95,
        "Recalculation timing differs (query vs engine render)",
    ),
    ("Pi", "Pi()", "number", "PI", "PI()", 0.98, ""),
    (
        "BitCount",
        "BitCount(n)",
        "number",
        None,
        None,
        0.3,
        "No DAX bit functions; push upstream or Power Query",
    ),
    # interpretation (parse) functions
    (
        "Num#",
        "Num#(text, [format])",
        "format",
        "VALUE",
        "VALUE({0})",
        0.85,
        "Qlik format-code argument has no DAX analogue; locale review",
    ),
    (
        "Date#",
        "Date#(text, [format])",
        "format",
        "DATEVALUE",
        "DATEVALUE({0})",
        0.80,
        "Format-code driven parsing differs; prefer typed columns in Power Query",
    ),
    ("Time#", "Time#(text, [format])", "format", "TIMEVALUE", "TIMEVALUE({0})", 0.80, ""),
    (
        "Timestamp#",
        "Timestamp#(text, [format])",
        "format",
        None,
        None,
        0.5,
        "Compose DATEVALUE + TIMEVALUE or parse in Power Query",
    ),
    (
        "Interval",
        "Interval(value, [format])",
        "format",
        "FORMAT",
        'FORMAT({0}, "hh:mm:ss")',
        0.70,
        "Interval display semantics differ",
    ),
    (
        "Evaluate",
        "Evaluate(text)",
        "script",
        None,
        None,
        0.15,
        "Dynamic expression evaluation has no DAX analogue — redesign",
    ),
    # date/name duals & period starts
    (
        "MonthName",
        "MonthName(date)",
        "date",
        "FORMAT",
        'FORMAT({0}, "MMM yyyy")',
        0.85,
        "Returns text, not a dual; pair with a sort column",
    ),
    (
        "QuarterName",
        "QuarterName(date)",
        "date",
        "FORMAT",
        'FORMAT({0}, "MMM") & "-" & FORMAT({0}, "yyyy")',
        0.70,
        "Qlik shows quarter month range; usually replaced by date-table column",
    ),
    ("YearName", "YearName(date)", "date", "FORMAT", 'FORMAT({0}, "yyyy")', 0.85, ""),
    ("DayName", "DayName(date)", "date", "FORMAT", 'FORMAT({0}, "dddd")', 0.85, ""),
    (
        "WeekName",
        "WeekName(date)",
        "date",
        None,
        None,
        0.5,
        "Week-year/week-number label; build in the date table",
    ),
    ("DayStart", "DayStart(ts)", "date", "TRUNC", "TRUNC({0})", 0.88, ""),
    (
        "DayEnd",
        "DayEnd(ts)",
        "date",
        None,
        "TRUNC({0}) + 1 - (1 / 86400)",
        0.65,
        "End-of-interval semantics; review tick precision",
    ),
    ("GMT", "GMT()", "date", "UTCNOW", "UTCNOW()", 0.85, ""),
    ("UTC", "UTC()", "date", "UTCNOW", "UTCNOW()", 0.90, ""),
    (
        "LocalTime",
        "LocalTime([tz])",
        "date",
        None,
        None,
        0.4,
        "Timezone-aware now: no DAX analogue, handle in Power Query or the source",
    ),
    (
        "ConvertToLocalTime",
        "ConvertToLocalTime(ts, place)",
        "date",
        None,
        None,
        0.3,
        "Timezone conversion belongs in Power Query / upstream",
    ),
    (
        "DayNumberOfYear",
        "DayNumberOfYear(date)",
        "date",
        None,
        "DATEDIFF(DATE(YEAR({0}), 1, 1), {0}, DAY) + 1",
        0.88,
        "",
    ),
    (
        "DayNumberOfQuarter",
        "DayNumberOfQuarter(date)",
        "date",
        None,
        "DATEDIFF(DATE(YEAR({0}), 3 * QUARTER({0}) - 2, 1), {0}, DAY) + 1",
        0.80,
        "",
    ),
    (
        "SetDateYear",
        "SetDateYear(date, year)",
        "date",
        None,
        "DATE({1}, MONTH({0}), DAY({0}))",
        0.75,
        "Feb-29 edge cases",
    ),
    (
        "SetDateYearMonth",
        "SetDateYearMonth(date, year, month)",
        "date",
        None,
        "DATE({1}, {2}, DAY({0}))",
        0.70,
        "Month-length edge cases",
    ),
    (
        "FirstWorkDate",
        "FirstWorkDate(end, days, [holidays])",
        "date",
        None,
        None,
        0.35,
        "Workday arithmetic: compose with NETWORKDAYS or a date-table flag column",
    ),
    ("LastWorkDate", "LastWorkDate(start, days, [holidays])", "date", None, None, 0.35, "As FirstWorkDate"),
    # string additions
    (
        "TextBetween",
        "TextBetween(s, before, after)",
        "string",
        None,
        "MID({0}, SEARCH({1}, {0}, 1, 0) + LEN({1}), "
        "SEARCH({2}, {0}, 1, 0) - SEARCH({1}, {0}, 1, 0) - LEN({1}))",
        0.62,
        "Composed; not-found semantics differ — review",
    ),
    (
        "SubStringCount",
        "SubStringCount(s, substring)",
        "string",
        None,
        'DIVIDE(LEN({0}) - LEN(SUBSTITUTE({0}, {1}, "")), LEN({1}))',
        0.75,
        "",
    ),
    (
        "Hash128",
        "Hash128(expr...)",
        "string",
        None,
        None,
        0.2,
        "No hashing in DAX; hash in Power Query or upstream",
    ),
    ("Hash256", "Hash256(expr...)", "string", None, None, 0.2, "As Hash128"),
    (
        "AutoNumber",
        "AutoNumber(expr, [id])",
        "script",
        None,
        None,
        0.4,
        "Load-script surrogate keys -> Power Query index/merge keys",
    ),
    # logical / type tests
    ("IsNum", "IsNum(expr)", "logical", "ISNUMBER", "ISNUMBER({0})", 0.92, ""),
    ("IsText", "IsText(expr)", "logical", "ISTEXT", "ISTEXT({0})", 0.90, ""),
    # range / selection extensions
    (
        "RangeCount",
        "RangeCount(a, b, ...)",
        "range",
        None,
        None,
        0.5,
        "Count of non-null scalars; compose with COALESCE flags",
    ),
    (
        "RangeStdev",
        "RangeStdev(a, b, ...)",
        "range",
        None,
        None,
        0.4,
        "Row-scalar stdev: restructure to a column and aggregate",
    ),
    ("RangeFractile", "RangeFractile(f, a, b, ...)", "range", None, None, 0.35, "As RangeStdev"),
    (
        "GetPossibleCount",
        "GetPossibleCount(field)",
        "ui",
        None,
        "COUNTROWS(VALUES({0}))",
        0.60,
        "Possible vs selected semantics differ",
    ),
    (
        "GetExcludedCount",
        "GetExcludedCount(field)",
        "ui",
        None,
        None,
        0.25,
        "Excluded-state count has no filter-context analogue",
    ),
]
