"""Spotfire expression-language function reference with DAX mappings.

Tuple shape: (name, signature, category, dax_equivalent, dax_template, confidence, notes)

OVER expressions and THEN post-aggregation are handled structurally by
the Spotfire translator; node-navigation methods used inside OVER
(AllPrevious, Intersect, NavigatePeriod...) are listed so the translator
can cite per-method confidence.
"""

SPOTFIRE_FUNCTIONS: list[tuple] = [
    # ---- aggregation ----
    ("Sum", "Sum([col])", "aggregate", "SUM", "SUM({0})", 0.97, ""),
    ("Avg", "Avg([col])", "aggregate", "AVERAGE", "AVERAGE({0})", 0.95, ""),
    ("Min", "Min([col])", "aggregate", "MIN", "MIN({0})", 0.95, ""),
    ("Max", "Max([col])", "aggregate", "MAX", "MAX({0})", 0.95, ""),
    ("Count", "Count([col])", "aggregate", "COUNT", "COUNT({0})", 0.95, ""),
    ("UniqueCount", "UniqueCount([col])", "aggregate", "DISTINCTCOUNT", "DISTINCTCOUNT({0})", 0.95, ""),
    ("Median", "Median([col])", "aggregate", "MEDIAN", "MEDIAN({0})", 0.95, ""),
    ("StdDev", "StdDev([col])", "aggregate", "STDEV.S", "STDEV.S({0})", 0.95, ""),
    ("Var", "Var([col])", "aggregate", "VAR.S", "VAR.S({0})", 0.95, ""),
    (
        "Percentile",
        "Percentile([col], p)",
        "aggregate",
        "PERCENTILE.INC",
        "PERCENTILE.INC({0}, {1} / 100)",
        0.90,
        "Spotfire uses 0-100; DAX 0-1",
    ),
    (
        "First",
        "First([col])",
        "aggregate",
        None,
        "MINX(TOPN(1, ALLSELECTED(), [RowId], ASC), {0})",
        0.55,
        "Data-order dependent; verify ordering column",
    ),
    (
        "Last",
        "Last([col])",
        "aggregate",
        None,
        "MAXX(TOPN(1, ALLSELECTED(), [RowId], DESC), {0})",
        0.55,
        "Data-order dependent",
    ),
    (
        "ValueForMax",
        "ValueForMax([max_col], [val_col])",
        "aggregate",
        None,
        "MAXX(TOPN(1, ALLSELECTED(), {0}, DESC), {1})",
        0.70,
        "",
    ),
    (
        "ValueForMin",
        "ValueForMin([min_col], [val_col])",
        "aggregate",
        None,
        "MAXX(TOPN(1, ALLSELECTED(), {0}, ASC), {1})",
        0.70,
        "",
    ),
    (
        "Concatenate",
        "Concatenate([col], [sep])",
        "aggregate",
        "CONCATENATEX",
        "CONCATENATEX(VALUES({0}), {0}, {1})",
        0.88,
        "",
    ),
    ("GeometricMean", "GeometricMean([col])", "aggregate", "GEOMEAN", "GEOMEAN({0})", 0.92, ""),
    ("Product", "Product([col])", "aggregate", "PRODUCT", "PRODUCT({0})", 0.95, ""),
    # ---- logical ----
    ("If", "If(cond, then, [else])", "logical", "IF", "IF({0}, {1}, {2})", 0.95, ""),
    (
        "Case",
        "Case WHEN cond THEN v ... END",
        "logical",
        "SWITCH",
        None,
        0.90,
        "Handled structurally by the AST emitter",
    ),
    ("SN", "SN(expr, substitute)", "logical", "COALESCE", "COALESCE({0}, {1})", 0.95, "Substitute-null"),
    # ---- numeric ----
    ("Abs", "Abs(x)", "number", "ABS", "ABS({0})", 0.98, ""),
    ("Ceiling", "Ceiling(x)", "number", "CEILING", "CEILING({0}, 1)", 0.95, ""),
    ("Floor", "Floor(x)", "number", "FLOOR", "FLOOR({0}, 1)", 0.95, ""),
    ("Round", "Round(x, n)", "number", "ROUND", "ROUND({0}, {1})", 0.97, ""),
    ("Exp", "Exp(x)", "number", "EXP", "EXP({0})", 0.98, ""),
    ("Ln", "Ln(x)", "number", "LN", "LN({0})", 0.98, ""),
    ("Log10", "Log10(x)", "number", "LOG10", "LOG10({0})", 0.98, ""),
    ("Power", "Power(x, y)", "number", "POWER", "POWER({0}, {1})", 0.98, ""),
    ("Sqrt", "Sqrt(x)", "number", "SQRT", "SQRT({0})", 0.98, ""),
    ("Mod", "Mod(x, y)", "number", "MOD", "MOD({0}, {1})", 0.95, ""),
    ("Sin", "Sin(x)", "number", "SIN", "SIN({0})", 0.98, ""),
    ("Cos", "Cos(x)", "number", "COS", "COS({0})", 0.98, ""),
    ("Tan", "Tan(x)", "number", "TAN", "TAN({0})", 0.98, ""),
    # ---- string ----
    ("Left", "Left(s, n)", "string", "LEFT", "LEFT({0}, {1})", 0.98, ""),
    ("Right", "Right(s, n)", "string", "RIGHT", "RIGHT({0}, {1})", 0.98, ""),
    ("Mid", "Mid(s, start, len)", "string", "MID", "MID({0}, {1}, {2})", 0.95, ""),
    ("Len", "Len(s)", "string", "LEN", "LEN({0})", 0.98, ""),
    ("Lower", "Lower(s)", "string", "LOWER", "LOWER({0})", 0.98, ""),
    ("Upper", "Upper(s)", "string", "UPPER", "UPPER({0})", 0.98, ""),
    ("Trim", "Trim(s)", "string", "TRIM", "TRIM({0})", 0.95, ""),
    (
        "Substitute",
        "Substitute(s, find, replace)",
        "string",
        "SUBSTITUTE",
        "SUBSTITUTE({0}, {1}, {2})",
        0.95,
        "",
    ),
    ("Find", "Find(substring, s)", "string", "SEARCH", "SEARCH({0}, {1}, 1, 0)", 0.90, ""),
    ("Repeat", "Repeat(s, n)", "string", "REPT", "REPT({0}, {1})", 0.95, ""),
    ("Concatenate_str", "Concatenate(s1, s2, ...)", "string", "CONCATENATE", "{0} & {1}", 0.95, ""),
    (
        "RXReplace",
        "RXReplace(s, pattern, replace, opts)",
        "string",
        None,
        None,
        0.3,
        "No regex in DAX; Power Query or upstream SQL",
    ),
    ("RXExtract", "RXExtract(s, pattern, n)", "string", None, None, 0.3, "As RXReplace"),
    # ---- date ----
    (
        "DateAdd",
        "DateAdd(part, n, date)",
        "date",
        None,
        None,
        0.80,
        "Emitter maps part keyword to EDATE/date arithmetic per unit",
    ),
    ("DateDiff", "DateDiff(part, start, end)", "date", "DATEDIFF", "DATEDIFF({1}, {2}, {0})", 0.90, ""),
    (
        "DatePart",
        "DatePart(part, date)",
        "date",
        None,
        None,
        0.85,
        "Maps to YEAR/MONTH/DAY/... chosen by the emitter",
    ),
    ("DateTimeNow", "DateTimeNow()", "date", "NOW", "NOW()", 0.98, ""),
    ("Today", "Today()", "date", "TODAY", "TODAY()", 0.98, ""),
    ("Year", "Year(date)", "date", "YEAR", "YEAR({0})", 0.98, ""),
    ("Month", "Month(date)", "date", "MONTH", "MONTH({0})", 0.95, ""),
    ("Day", "Day(date)", "date", "DAY", "DAY({0})", 0.98, ""),
    ("Hour", "Hour(ts)", "date", "HOUR", "HOUR({0})", 0.98, ""),
    ("Minute", "Minute(ts)", "date", "MINUTE", "MINUTE({0})", 0.98, ""),
    ("Second", "Second(ts)", "date", "SECOND", "SECOND({0})", 0.98, ""),
    ("Quarter", "Quarter(date)", "date", "QUARTER", "QUARTER({0})", 0.95, ""),
    ("Week", "Week(date)", "date", "WEEKNUM", "WEEKNUM({0})", 0.88, "Week conventions differ"),
    (
        "DayOfWeek",
        "DayOfWeek(date)",
        "date",
        "WEEKDAY",
        "WEEKDAY({0})",
        0.90,
        "Numbering convention must be aligned",
    ),
    ("DayOfYear", "DayOfYear(date)", "date", None, "DATEDIFF(DATE(YEAR({0}), 1, 1), {0}, DAY) + 1", 0.90, ""),
    (
        "Date",
        "Date(y, m, d) or Date(s)",
        "date",
        "DATE",
        "DATE({0}, {1}, {2})",
        0.90,
        "Single-arg string form maps to DATEVALUE",
    ),
    # ---- ranking / row ----
    (
        "Rank",
        "Rank(expr, [order], [partition])",
        "ranking",
        "RANKX",
        "RANKX(ALLSELECTED(), {0})",
        0.75,
        "Verify partition columns map to visual scope",
    ),
    (
        "DenseRank",
        "DenseRank(expr, ...)",
        "ranking",
        "RANKX",
        "RANKX(ALLSELECTED(), {0}, , DESC, DENSE)",
        0.75,
        "",
    ),
    (
        "RowId",
        "RowId()",
        "ranking",
        None,
        None,
        0.5,
        "Add an index column in Power Query; no row identity in DAX visuals",
    ),
    (
        "BinByDateTime",
        "BinByDateTime([col], part, n)",
        "ranking",
        None,
        None,
        0.5,
        "Replace with date-table hierarchy levels",
    ),
    # ---- OVER navigation methods (structural; per-method confidence) ----
    (
        "All",
        "OVER (All([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, ALLSELECTED({1}))",
        0.80,
        "Percent-of-total style",
    ),
    (
        "AllPrevious",
        "OVER (AllPrevious([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, FILTER(ALLSELECTED({1}), {1} <= MAX({1})))",
        0.75,
        "Running-total pattern; requires ordered axis column",
    ),
    (
        "AllNext",
        "OVER (AllNext([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, FILTER(ALLSELECTED({1}), {1} >= MIN({1})))",
        0.75,
        "",
    ),
    (
        "Previous",
        "OVER (Previous([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, OFFSET(-1, ORDERBY({1})))",
        0.65,
        "OFFSET needs explicit axis",
    ),
    ("Next", "OVER (Next([Axis.X]))", "over", None, "CALCULATE({0}, OFFSET(1, ORDERBY({1})))", 0.65, ""),
    (
        "Parent",
        "OVER (Parent([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, REMOVEFILTERS({1}))",
        0.70,
        "Removes the innermost hierarchy level",
    ),
    (
        "Intersect",
        "OVER (Intersect(a, b))",
        "over",
        None,
        None,
        0.55,
        "Multi-hierarchy intersection: CALCULATE with multiple filter args; custom hierarchies "
        "require mandatory review (ASSISTED)",
    ),
    (
        "PreviousPeriod",
        "OVER (PreviousPeriod([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, PREVIOUSMONTH({1}))",
        0.65,
        "Period granularity inferred from axis; requires marked date table",
    ),
    (
        "NextPeriod",
        "OVER (NextPeriod([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, NEXTMONTH({1}))",
        0.65,
        "As PreviousPeriod",
    ),
    (
        "ParallelPeriod",
        "OVER (ParallelPeriod([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, SAMEPERIODLASTYEAR({1}))",
        0.70,
        "Requires marked date table",
    ),
    (
        "NavigatePeriod",
        "OVER (NavigatePeriod([Axis.X], part, n, [level]))",
        "over",
        None,
        "CALCULATE({0}, DATEADD({1}, n, <unit>))",
        0.60,
        "General period navigation; each instance needs review of unit + level args",
    ),
    (
        "LastPeriods",
        "OVER (LastPeriods(n, [Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, DATESINPERIOD({1}, MAX({1}), -n, MONTH))",
        0.65,
        "Moving-window aggregate; unit inferred from axis",
    ),
    (
        "PreviousYear",
        "OVER (PreviousYear([Axis.X]))",
        "over",
        None,
        "CALCULATE({0}, SAMEPERIODLASTYEAR({1}))",
        0.70,
        "",
    ),
    # ---- properties / document ----
    (
        "DocumentProperty",
        'DocumentProperty("name")',
        "property",
        None,
        None,
        0.6,
        "Map to What-if parameter or field parameter depending on usage",
    ),
    ("CurrentDataTable", "CurrentDataTableName()", "property", None, None, 0.3, "No analogue"),
]
