"""Tableau function reference with DAX mappings.

Tuple shape: (name, signature, category, dax_equivalent, dax_template, confidence, notes)
Aggregates assume measure context; table calculations assume a visual-calc
or WINDOW-function rewrite and are capped at ASSISTED confidence because
Tableau's partitioning/addressing has no 1:1 DAX analogue.
"""

TABLEAU_FUNCTIONS: list[tuple] = [
    # ---- number ----
    ("ABS", "ABS(number)", "number", "ABS", "ABS({0})", 0.98, ""),
    ("ACOS", "ACOS(number)", "number", "ACOS", "ACOS({0})", 0.98, ""),
    ("ASIN", "ASIN(number)", "number", "ASIN", "ASIN({0})", 0.98, ""),
    ("ATAN", "ATAN(number)", "number", "ATAN", "ATAN({0})", 0.98, ""),
    (
        "ATAN2",
        "ATAN2(y, x)",
        "number",
        "ATAN",
        "ATAN(DIVIDE({0}, {1}))",
        0.80,
        "DAX has no two-argument ATAN2; quadrant handling needs review",
    ),
    ("CEILING", "CEILING(number)", "number", "CEILING", "CEILING({0}, 1)", 0.95, ""),
    ("COS", "COS(number)", "number", "COS", "COS({0})", 0.98, ""),
    ("COT", "COT(number)", "number", "COT", "COT({0})", 0.98, ""),
    ("DEGREES", "DEGREES(number)", "number", "DEGREES", "DEGREES({0})", 0.98, ""),
    ("DIV", "DIV(int1, int2)", "number", "QUOTIENT", "QUOTIENT({0}, {1})", 0.95, ""),
    ("EXP", "EXP(number)", "number", "EXP", "EXP({0})", 0.98, ""),
    ("FLOOR", "FLOOR(number)", "number", "FLOOR", "FLOOR({0}, 1)", 0.95, ""),
    (
        "HEXBINX",
        "HEXBINX(x, y)",
        "number",
        None,
        None,
        0.2,
        "No DAX equivalent; recompute hex binning upstream in Power Query or SQL",
    ),
    (
        "HEXBINY",
        "HEXBINY(x, y)",
        "number",
        None,
        None,
        0.2,
        "No DAX equivalent; recompute hex binning upstream in Power Query or SQL",
    ),
    ("LN", "LN(number)", "number", "LN", "LN({0})", 0.98, ""),
    (
        "LOG",
        "LOG(number, [base])",
        "number",
        "LOG",
        "LOG({0}, {1})",
        0.95,
        "Tableau default base is 10; DAX LOG default base is e — emit base explicitly",
    ),
    ("PI", "PI()", "number", "PI", "PI()", 0.98, ""),
    ("POWER", "POWER(number, power)", "number", "POWER", "POWER({0}, {1})", 0.98, ""),
    ("RADIANS", "RADIANS(number)", "number", "RADIANS", "RADIANS({0})", 0.98, ""),
    ("ROUND", "ROUND(number, [decimals])", "number", "ROUND", "ROUND({0}, {1})", 0.97, ""),
    ("SIGN", "SIGN(number)", "number", "SIGN", "SIGN({0})", 0.98, ""),
    ("SIN", "SIN(number)", "number", "SIN", "SIN({0})", 0.98, ""),
    ("SQRT", "SQRT(number)", "number", "SQRT", "SQRT({0})", 0.98, ""),
    ("SQUARE", "SQUARE(number)", "number", None, "({0}) ^ 2", 0.95, "Emitted as power expression"),
    ("TAN", "TAN(number)", "number", "TAN", "TAN({0})", 0.98, ""),
    ("ZN", "ZN(expression)", "number", "COALESCE", "COALESCE({0}, 0)", 0.95, ""),
    # ---- string ----
    (
        "ASCII",
        "ASCII(string)",
        "string",
        "UNICODE",
        "UNICODE({0})",
        0.92,
        "UNICODE returns the code point; identical for ASCII range",
    ),
    ("CHAR", "CHAR(integer)", "string", "UNICHAR", "UNICHAR({0})", 0.95, ""),
    (
        "CONTAINS",
        "CONTAINS(string, substring)",
        "string",
        "CONTAINSSTRING",
        "CONTAINSSTRING({0}, {1})",
        0.95,
        "DAX CONTAINSSTRING is case-insensitive",
    ),
    (
        "ENDSWITH",
        "ENDSWITH(string, substring)",
        "string",
        None,
        "RIGHT({0}, LEN({1})) = {1}",
        0.90,
        "Composed expression",
    ),
    (
        "FIND",
        "FIND(string, substring, [start])",
        "string",
        "SEARCH",
        "SEARCH({1}, {0}, {2}, 0)",
        0.90,
        "SEARCH returns 0 via fourth arg instead of erroring; argument order swaps",
    ),
    (
        "FINDNTH",
        "FINDNTH(string, substring, occurrence)",
        "string",
        None,
        None,
        0.3,
        "No native DAX; precompute in Power Query (Text.PositionOfAny) or redesign",
    ),
    ("LEFT", "LEFT(string, number)", "string", "LEFT", "LEFT({0}, {1})", 0.98, ""),
    ("LEN", "LEN(string)", "string", "LEN", "LEN({0})", 0.98, ""),
    ("LOWER", "LOWER(string)", "string", "LOWER", "LOWER({0})", 0.98, ""),
    (
        "LTRIM",
        "LTRIM(string)",
        "string",
        None,
        None,
        0.45,
        "DAX TRIM strips both ends and internal doubles; left-only trim needs Power Query",
    ),
    ("MID", "MID(string, start, [length])", "string", "MID", "MID({0}, {1}, {2})", 0.95, ""),
    (
        "PROPER",
        "PROPER(string)",
        "string",
        None,
        None,
        0.45,
        "No DAX PROPER; apply Text.Proper in Power Query at load time",
    ),
    (
        "REPLACE",
        "REPLACE(string, substring, replacement)",
        "string",
        "SUBSTITUTE",
        "SUBSTITUTE({0}, {1}, {2})",
        0.95,
        "",
    ),
    ("RIGHT", "RIGHT(string, number)", "string", "RIGHT", "RIGHT({0}, {1})", 0.98, ""),
    ("RTRIM", "RTRIM(string)", "string", None, None, 0.45, "Right-only trim needs Power Query Text.TrimEnd"),
    ("SPACE", "SPACE(number)", "string", "REPT", 'REPT(" ", {0})', 0.95, ""),
    (
        "SPLIT",
        "SPLIT(string, delimiter, token)",
        "string",
        "PATHITEM",
        'PATHITEM(SUBSTITUTE({0}, {1}, "|"), {2})',
        0.75,
        "PATH functions require '|' delimiter; fails if data contains '|'. Prefer Power Query split",
    ),
    (
        "STARTSWITH",
        "STARTSWITH(string, substring)",
        "string",
        None,
        "LEFT({0}, LEN({1})) = {1}",
        0.90,
        "Composed expression",
    ),
    (
        "TRIM",
        "TRIM(string)",
        "string",
        "TRIM",
        "TRIM({0})",
        0.95,
        "DAX TRIM also collapses internal repeated spaces",
    ),
    ("UPPER", "UPPER(string)", "string", "UPPER", "UPPER({0})", 0.98, ""),
    (
        "REGEXP_EXTRACT",
        "REGEXP_EXTRACT(string, pattern)",
        "string",
        None,
        None,
        0.3,
        "No regex in DAX; move to Power Query (limited) or upstream SQL",
    ),
    (
        "REGEXP_MATCH",
        "REGEXP_MATCH(string, pattern)",
        "string",
        None,
        None,
        0.3,
        "No regex in DAX; move to Power Query or upstream SQL",
    ),
    (
        "REGEXP_REPLACE",
        "REGEXP_REPLACE(string, pattern, replacement)",
        "string",
        None,
        None,
        0.3,
        "No regex in DAX; move to Power Query or upstream SQL",
    ),
    # ---- date ----
    (
        "DATEADD",
        "DATEADD(date_part, interval, date)",
        "date",
        "DATEADD",
        "DATEADD({2}, {1}, {0})",
        0.85,
        "DAX DATEADD works on contiguous date columns only; for scalar dates emit DATE math",
    ),
    (
        "DATEDIFF",
        "DATEDIFF(date_part, start, end)",
        "date",
        "DATEDIFF",
        "DATEDIFF({1}, {2}, {0})",
        0.90,
        "Interval keyword maps to DAX interval enum",
    ),
    (
        "DATENAME",
        "DATENAME(date_part, date)",
        "date",
        "FORMAT",
        "FORMAT({1}, {0})",
        0.85,
        "date_part maps to a FORMAT picture string (e.g. 'MMMM' for month)",
    ),
    (
        "DATEPART",
        "DATEPART(date_part, date)",
        "date",
        None,
        None,
        0.85,
        "Maps to the specific extractor (YEAR/MONTH/DAY/HOUR...) chosen by the emitter",
    ),
    (
        "DATETRUNC",
        "DATETRUNC(date_part, date)",
        "date",
        None,
        None,
        0.80,
        "Emit STARTOFMONTH/STARTOFQUARTER/STARTOFYEAR on date columns, or DATE() composition",
    ),
    ("DAY", "DAY(date)", "date", "DAY", "DAY({0})", 0.98, ""),
    (
        "ISDATE",
        "ISDATE(string)",
        "date",
        None,
        "NOT(ISERROR(DATEVALUE({0})))",
        0.85,
        "Composed via error-trapping",
    ),
    ("MAKEDATE", "MAKEDATE(year, month, day)", "date", "DATE", "DATE({0}, {1}, {2})", 0.97, ""),
    (
        "MAKEDATETIME",
        "MAKEDATETIME(date, time)",
        "date",
        None,
        "{0} + {1}",
        0.85,
        "Datetime arithmetic; verify timezone semantics",
    ),
    ("MAKETIME", "MAKETIME(hour, minute, second)", "date", "TIME", "TIME({0}, {1}, {2})", 0.97, ""),
    ("MONTH", "MONTH(date)", "date", "MONTH", "MONTH({0})", 0.98, ""),
    ("NOW", "NOW()", "date", "NOW", "NOW()", 0.98, ""),
    ("QUARTER", "QUARTER(date)", "date", "QUARTER", "QUARTER({0})", 0.97, ""),
    ("TODAY", "TODAY()", "date", "TODAY", "TODAY()", 0.98, ""),
    (
        "WEEK",
        "WEEK(date)",
        "date",
        "WEEKNUM",
        "WEEKNUM({0})",
        0.92,
        "Week-start convention may differ; verify locale settings",
    ),
    ("YEAR", "YEAR(date)", "date", "YEAR", "YEAR({0})", 0.98, ""),
    # ---- type conversion ----
    ("DATE", "DATE(expression)", "conversion", "DATEVALUE", "DATEVALUE({0})", 0.90, ""),
    (
        "DATETIME",
        "DATETIME(expression)",
        "conversion",
        None,
        "DATEVALUE({0}) + TIMEVALUE({0})",
        0.70,
        "Review per input shape",
    ),
    ("FLOAT", "FLOAT(expression)", "conversion", None, "VALUE({0}) * 1.0", 0.90, ""),
    (
        "INT",
        "INT(expression)",
        "conversion",
        "INT",
        "INT({0})",
        0.92,
        "Tableau INT truncates toward zero; DAX INT floors — differs for negatives, use TRUNC",
    ),
    ("STR", "STR(expression)", "conversion", "FORMAT", 'FORMAT({0}, "General")', 0.90, ""),
    # ---- logical ----
    (
        "IF",
        "IF test THEN x [ELSEIF...] [ELSE y] END",
        "logical",
        "IF",
        None,
        0.95,
        "Handled structurally by the AST emitter (IF / SWITCH chains)",
    ),
    (
        "IIF",
        "IIF(test, then, else, [unknown])",
        "logical",
        "IF",
        "IF({0}, {1}, {2})",
        0.92,
        "Fourth 'unknown' argument has no DAX analogue; flagged when present",
    ),
    (
        "CASE",
        "CASE expr WHEN v1 THEN r1 ... END",
        "logical",
        "SWITCH",
        None,
        0.95,
        "Handled structurally by the AST emitter",
    ),
    ("IFNULL", "IFNULL(expr1, expr2)", "logical", "COALESCE", "COALESCE({0}, {1})", 0.95, ""),
    ("ISNULL", "ISNULL(expression)", "logical", "ISBLANK", "ISBLANK({0})", 0.95, ""),
    ("AND", "expr1 AND expr2", "logical", "&&", "({0}) && ({1})", 0.97, ""),
    ("OR", "expr1 OR expr2", "logical", "||", "({0}) || ({1})", 0.97, ""),
    ("NOT", "NOT expression", "logical", "NOT", "NOT({0})", 0.97, ""),
    (
        "MIN",
        "MIN(expr) or MIN(a, b)",
        "aggregate",
        "MIN",
        "MIN({0})",
        0.92,
        "Two-arg scalar MIN(a,b) maps to MIN(a,b) in DAX as well",
    ),
    ("MAX", "MAX(expr) or MAX(a, b)", "aggregate", "MAX", "MAX({0})", 0.92, ""),
    # ---- aggregate ----
    (
        "ATTR",
        "ATTR(expression)",
        "aggregate",
        "SELECTEDVALUE",
        "SELECTEDVALUE({0})",
        0.80,
        "SELECTEDVALUE returns blank where ATTR shows '*'; review display expectations",
    ),
    ("AVG", "AVG(expression)", "aggregate", "AVERAGE", "AVERAGE({0})", 0.95, ""),
    (
        "CORR",
        "CORR(expr1, expr2)",
        "aggregate",
        None,
        None,
        0.5,
        "Compose with iterator math (covariance/stdev) or push upstream; review statistically",
    ),
    (
        "COUNT",
        "COUNT(expression)",
        "aggregate",
        "COUNT",
        "COUNT({0})",
        0.95,
        "COUNTROWS(table) when counting a table reference",
    ),
    ("COUNTD", "COUNTD(expression)", "aggregate", "DISTINCTCOUNT", "DISTINCTCOUNT({0})", 0.95, ""),
    (
        "COVAR",
        "COVAR(expr1, expr2)",
        "aggregate",
        None,
        None,
        0.5,
        "Compose with iterator math; review statistically",
    ),
    (
        "COVARP",
        "COVARP(expr1, expr2)",
        "aggregate",
        None,
        None,
        0.5,
        "Compose with iterator math; review statistically",
    ),
    ("MEDIAN", "MEDIAN(expression)", "aggregate", "MEDIAN", "MEDIAN({0})", 0.95, ""),
    (
        "PERCENTILE",
        "PERCENTILE(expression, number)",
        "aggregate",
        "PERCENTILE.INC",
        "PERCENTILE.INC({0}, {1})",
        0.92,
        "",
    ),
    ("STDEV", "STDEV(expression)", "aggregate", "STDEV.S", "STDEV.S({0})", 0.95, ""),
    ("STDEVP", "STDEVP(expression)", "aggregate", "STDEV.P", "STDEV.P({0})", 0.95, ""),
    ("SUM", "SUM(expression)", "aggregate", "SUM", "SUM({0})", 0.97, ""),
    ("VAR", "VAR(expression)", "aggregate", "VAR.S", "VAR.S({0})", 0.95, ""),
    ("VARP", "VARP(expression)", "aggregate", "VAR.P", "VAR.P({0})", 0.95, ""),
    # ---- table calculations (ASSISTED cap: partitioning differs) ----
    (
        "FIRST",
        "FIRST()",
        "table_calc",
        "INDEX",
        None,
        0.60,
        "Visual-relative offset; map to INDEX(1) window function with explicit ORDERBY/PARTITIONBY",
    ),
    (
        "INDEX",
        "INDEX()",
        "table_calc",
        "RANKX",
        None,
        0.65,
        "Map to RANKX over the visual's dimension or INDEX window function",
    ),
    (
        "LAST",
        "LAST()",
        "table_calc",
        "INDEX",
        None,
        0.60,
        "Map to INDEX(-1) window function with explicit ordering",
    ),
    (
        "LOOKUP",
        "LOOKUP(expression, [offset])",
        "table_calc",
        "OFFSET",
        "CALCULATE({0}, OFFSET({1}, ORDERBY([Date])))",
        0.65,
        "OFFSET needs explicit axis definition; Tableau's compute-using is implicit",
    ),
    (
        "PREVIOUS_VALUE",
        "PREVIOUS_VALUE(expression)",
        "table_calc",
        None,
        None,
        0.3,
        "Recursive reference has no DAX equivalent; redesign the calculation",
    ),
    (
        "RANK",
        "RANK(expression, ['asc'|'desc'])",
        "table_calc",
        "RANKX",
        "RANKX(ALLSELECTED(), {0})",
        0.75,
        "Confirm partitioning scope matches compute-using",
    ),
    (
        "RANK_DENSE",
        "RANK_DENSE(expression)",
        "table_calc",
        "RANKX",
        "RANKX(ALLSELECTED(), {0}, , DESC, DENSE)",
        0.75,
        "",
    ),
    (
        "RANK_MODIFIED",
        "RANK_MODIFIED(expression)",
        "table_calc",
        "RANKX",
        None,
        0.55,
        "Modified competition ranking needs a composed RANKX pattern; review",
    ),
    (
        "RANK_PERCENTILE",
        "RANK_PERCENTILE(expression)",
        "table_calc",
        None,
        "DIVIDE(RANKX(ALLSELECTED(), {0}, , ASC), COUNTROWS(ALLSELECTED()))",
        0.65,
        "",
    ),
    (
        "RANK_UNIQUE",
        "RANK_UNIQUE(expression)",
        "table_calc",
        "RANKX",
        None,
        0.60,
        "Tie-breaking is data-order dependent; review",
    ),
    (
        "RUNNING_AVG",
        "RUNNING_AVG(expression)",
        "table_calc",
        None,
        "AVERAGEX(WINDOW(1, ABS, 0, REL), {0})",
        0.70,
        "Requires explicit axis; verify ordering",
    ),
    (
        "RUNNING_COUNT",
        "RUNNING_COUNT(expression)",
        "table_calc",
        None,
        "COUNTX(WINDOW(1, ABS, 0, REL), {0})",
        0.70,
        "",
    ),
    (
        "RUNNING_MAX",
        "RUNNING_MAX(expression)",
        "table_calc",
        None,
        "MAXX(WINDOW(1, ABS, 0, REL), {0})",
        0.70,
        "",
    ),
    (
        "RUNNING_MIN",
        "RUNNING_MIN(expression)",
        "table_calc",
        None,
        "MINX(WINDOW(1, ABS, 0, REL), {0})",
        0.70,
        "",
    ),
    (
        "RUNNING_SUM",
        "RUNNING_SUM(expression)",
        "table_calc",
        None,
        "SUMX(WINDOW(1, ABS, 0, REL), {0})",
        0.75,
        "Running total over visual order; alternative CALCULATE+FILTER pattern on dates",
    ),
    ("SIZE", "SIZE()", "table_calc", "COUNTROWS", "COUNTROWS(ALLSELECTED())", 0.70, ""),
    (
        "TOTAL",
        "TOTAL(aggregate)",
        "table_calc",
        None,
        "CALCULATE({0}, ALLSELECTED())",
        0.80,
        "Grand total within visual context",
    ),
    (
        "WINDOW_AVG",
        "WINDOW_AVG(expr, [start, end])",
        "table_calc",
        None,
        "AVERAGEX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "Window frame mapping requires explicit ORDERBY",
    ),
    (
        "WINDOW_CORR",
        "WINDOW_CORR(expr1, expr2)",
        "table_calc",
        None,
        None,
        0.3,
        "Compose manually; statistical review required",
    ),
    (
        "WINDOW_COUNT",
        "WINDOW_COUNT(expr, [start, end])",
        "table_calc",
        None,
        "COUNTX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "",
    ),
    (
        "WINDOW_COVAR",
        "WINDOW_COVAR(expr1, expr2)",
        "table_calc",
        None,
        None,
        0.3,
        "Compose manually; statistical review required",
    ),
    (
        "WINDOW_MAX",
        "WINDOW_MAX(expr, [start, end])",
        "table_calc",
        None,
        "MAXX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "",
    ),
    (
        "WINDOW_MEDIAN",
        "WINDOW_MEDIAN(expr, [start, end])",
        "table_calc",
        None,
        "MEDIANX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "",
    ),
    (
        "WINDOW_MIN",
        "WINDOW_MIN(expr, [start, end])",
        "table_calc",
        None,
        "MINX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "",
    ),
    (
        "WINDOW_PERCENTILE",
        "WINDOW_PERCENTILE(expr, number)",
        "table_calc",
        None,
        None,
        0.5,
        "Compose PERCENTILEX.INC over WINDOW; review",
    ),
    (
        "WINDOW_STDEV",
        "WINDOW_STDEV(expr, [start, end])",
        "table_calc",
        None,
        "STDEVX.S(WINDOW({1}, REL, {2}, REL), {0})",
        0.65,
        "",
    ),
    (
        "WINDOW_SUM",
        "WINDOW_SUM(expr, [start, end])",
        "table_calc",
        None,
        "SUMX(WINDOW({1}, REL, {2}, REL), {0})",
        0.70,
        "",
    ),
    # ---- user / security ----
    (
        "USERNAME",
        "USERNAME()",
        "user",
        "USERPRINCIPALNAME",
        "USERPRINCIPALNAME()",
        0.85,
        "Returns UPN not Tableau username; RLS role rules must use UPN format",
    ),
    (
        "FULLNAME",
        "FULLNAME()",
        "user",
        "USERPRINCIPALNAME",
        "USERPRINCIPALNAME()",
        0.70,
        "No display-name function in RLS context; map via a users dimension table",
    ),
    (
        "ISMEMBEROF",
        "ISMEMBEROF(group)",
        "user",
        None,
        None,
        0.5,
        "Map to RLS role membership (AAD groups) — role design, not an expression rewrite",
    ),
    (
        "ISFULLNAME",
        "ISFULLNAME(name)",
        "user",
        None,
        "USERPRINCIPALNAME() = {0}",
        0.65,
        "Compare against UPN; name format differs",
    ),
    (
        "USERDOMAIN",
        "USERDOMAIN()",
        "user",
        None,
        None,
        0.4,
        "Derive from USERPRINCIPALNAME() suffix or a users dimension",
    ),
    # ---- script / external ----
    (
        "SCRIPT_REAL",
        "SCRIPT_REAL(code, args)",
        "script",
        None,
        None,
        0.1,
        "External R/Python service call; rebuild in Fabric notebooks / Python visuals — MANUAL",
    ),
    ("SCRIPT_INT", "SCRIPT_INT(code, args)", "script", None, None, 0.1, "As SCRIPT_REAL"),
    ("SCRIPT_STR", "SCRIPT_STR(code, args)", "script", None, None, 0.1, "As SCRIPT_REAL"),
    ("SCRIPT_BOOL", "SCRIPT_BOOL(code, args)", "script", None, None, 0.1, "As SCRIPT_REAL"),
]

# -- expansion wave 2: remaining window stats, spatial & analytics functions.
TABLEAU_FUNCTIONS += [
    (
        "WINDOW_VAR",
        "WINDOW_VAR(expr, [start, end])",
        "table_calc",
        None,
        "VARX.S(WINDOW({1}, REL, {2}, REL), {0})",
        0.65,
        "",
    ),
    (
        "WINDOW_VARP",
        "WINDOW_VARP(expr, [start, end])",
        "table_calc",
        None,
        "VARX.P(WINDOW({1}, REL, {2}, REL), {0})",
        0.65,
        "",
    ),
    (
        "DATEPARSE",
        "DATEPARSE(format, string)",
        "date",
        None,
        None,
        0.45,
        "Format-string parsing: type the column in Power Query instead",
    ),
    (
        "MAKEPOINT",
        "MAKEPOINT(lat, lon)",
        "spatial",
        None,
        None,
        0.2,
        "Spatial type: Azure Maps visual consumes lat/lon columns directly",
    ),
    (
        "MAKELINE",
        "MAKELINE(geom1, geom2)",
        "spatial",
        None,
        None,
        0.15,
        "No DAX spatial types; pre-compute geometry upstream",
    ),
    (
        "DISTANCE",
        "DISTANCE(geom1, geom2, unit)",
        "spatial",
        None,
        None,
        0.2,
        "Haversine in Power Query/SQL, or Azure Maps",
    ),
    (
        "BUFFER",
        "BUFFER(geom, distance, unit)",
        "spatial",
        None,
        None,
        0.15,
        "Pre-compute upstream; no DAX equivalent",
    ),
    (
        "MODEL_QUANTILE",
        "MODEL_QUANTILE(quantile, target, predictors)",
        "analytics",
        None,
        None,
        0.1,
        "Tableau predictive modeling: rebuild in Fabric notebooks / AutoML",
    ),
    (
        "MODEL_PERCENTILE",
        "MODEL_PERCENTILE(target, predictors)",
        "analytics",
        None,
        None,
        0.1,
        "As MODEL_QUANTILE",
    ),
]
