"""Feature Mapping Repository seed matrix (Section 4 / 5).

Tuple shape per row:
(feature_name, source_layer, powerbi_equivalent, migration_complexity,
 automation_possibility, fallback_strategy, confidence_score, notes,
 example_source, example_target)

powerbi_equivalent None == no native equivalent (fallback mandatory).
Confidence drives the AUTO/ASSISTED/MANUAL tier via the shared policy.
"""

TABLEAU_MAPPINGS: list[tuple] = [
    # workbook layer
    (
        "Workbook",
        "workbook",
        "PBIP project (report + semantic model)",
        "simple",
        "full",
        "",
        0.95,
        "1 workbook -> 1 PBIP project",
        ".twb/.twbx",
        "PBIP folder",
    ),
    (
        "Project (Server folder)",
        "workbook",
        "Fabric workspace / folder",
        "simple",
        "full",
        "",
        0.92,
        "Workspace structure mapping",
        "Server project",
        "Workspace",
    ),
    (
        "Workbook permissions",
        "workbook",
        "Workspace roles + app audiences",
        "medium",
        "partial",
        "Export permission matrix; rebuild as workspace roles — model differs (item-level vs workspace-level)",
        0.65,
        "Tableau is item-level, Fabric mostly workspace-level",
        None,
        None,
    ),
    (
        "Workbook metadata/tags",
        "workbook",
        "Endorsement + sensitivity labels + descriptions",
        "simple",
        "partial",
        "Carry tags into item descriptions where no native slot exists",
        0.75,
        "",
        None,
        None,
    ),
    # dashboard layer
    (
        "Dashboard",
        "dashboard",
        "Report page",
        "simple",
        "full",
        "",
        0.92,
        "Layout zones -> visual placement (best effort)",
        "Dashboard",
        "Report page",
    ),
    (
        "Story",
        "dashboard",
        "Report page sequence + bookmarks",
        "medium",
        "partial",
        "Generate one page per story point + bookmark navigator",
        0.70,
        "Story points have no native equivalent",
        "Story",
        "Bookmark navigator",
    ),
    ("Worksheet", "dashboard", "Visual on a report page", "simple", "full", "", 0.92, "", None, None),
    (
        "Filter action",
        "dashboard",
        "Cross-filtering / drillthrough",
        "simple",
        "partial",
        "Default cross-filter covers most cases; explicit target sheets -> drillthrough pages",
        0.80,
        "",
        "Filter action",
        "Cross-filter interaction",
    ),
    (
        "Highlight action",
        "dashboard",
        "Cross-highlight (default interaction)",
        "simple",
        "full",
        "",
        0.88,
        "",
        None,
        None,
    ),
    (
        "URL action",
        "dashboard",
        "URL on visual (conditional formatting web URL) / button",
        "medium",
        "partial",
        "Field-parameterized URLs -> DAX-built URL measure + button",
        0.70,
        "",
        None,
        None,
    ),
    (
        "Navigation action",
        "dashboard",
        "Page navigation button / bookmark",
        "simple",
        "partial",
        "Page navigator buttons",
        0.80,
        "",
        None,
        None,
    ),
    # visual layer
    (
        "Bar/Line/Area/Pie/Scatter charts",
        "visual",
        "Native core visuals",
        "simple",
        "full",
        "",
        0.95,
        "",
        None,
        None,
    ),
    (
        "Map (filled/symbol)",
        "visual",
        "Azure Map / filled map visual",
        "medium",
        "partial",
        "Custom territories and geocoding roles need rebuild; verify geographic role mapping",
        0.72,
        "",
        None,
        None,
    ),
    (
        "Tree map / Heat map / Histogram / Box plot / Waterfall / Funnel",
        "visual",
        "Native visuals (histogram via grouped column)",
        "simple",
        "partial",
        "Histogram needs binning measure or Power Query bins",
        0.82,
        "",
        None,
        None,
    ),
    (
        "Gantt",
        "visual",
        "Custom visual (marketplace) or stacked bar technique",
        "medium",
        "partial",
        "Stacked-bar Gantt technique; certified custom visual where allowed",
        0.65,
        "",
        None,
        None,
    ),
    (
        "Bullet graph",
        "visual",
        "KPI visual / bullet chart custom visual",
        "medium",
        "partial",
        "Rebuild with target lines on bar chart",
        0.68,
        "",
        None,
        None,
    ),
    (
        "Dual axis / combo",
        "visual",
        "Line and column combo chart",
        "simple",
        "partial",
        "Non line+column dual-axis combos need redesign (e.g. dual maps)",
        0.78,
        "",
        None,
        None,
    ),
    (
        "Packed bubbles",
        "visual",
        "Scatter with size / custom visual",
        "medium",
        "partial",
        "Approximate with scatter; exact packing layout is not reproducible",
        0.62,
        "",
        None,
        None,
    ),
    (
        "KPI cards (BANs)",
        "visual",
        "Card / multi-row card / new card visual",
        "simple",
        "full",
        "",
        0.90,
        "",
        None,
        None,
    ),
    (
        "Custom viz extensions",
        "visual",
        None,
        "very_complex",
        "manual",
        "Inventory the extension, find a certified custom visual or rebuild as native; document UX delta",
        0.20,
        "MANUAL tier always (Section 13)",
        None,
        None,
    ),
    # calculation layer
    (
        "Calculated field (row-level)",
        "calculation",
        "Calculated column or measure",
        "simple",
        "full",
        "",
        0.88,
        "Routed by aggregation analysis: row-level -> column, aggregate -> measure",
        "[Price] * [Qty]",
        "Sales[Price] * Sales[Qty]",
    ),
    (
        "Aggregate calculation",
        "calculation",
        "DAX measure",
        "simple",
        "full",
        "",
        0.90,
        "SUM/AVG/COUNTD etc. map directly",
        "SUM([Sales])",
        "SUM(Sales[Sales])",
    ),
    (
        "LOD FIXED",
        "calculation",
        "CALCULATE + ALLEXCEPT / REMOVEFILTERS",
        "complex",
        "partial",
        "Emit CALCULATE pattern; flag filter-context differences for review",
        0.75,
        "",
        "{FIXED [Cust]: SUM([Sales])}",
        "CALCULATE(SUM(Sales[Sales]), ALLEXCEPT(Sales, Sales[Cust]))",
    ),
    (
        "LOD INCLUDE/EXCLUDE",
        "calculation",
        "Iterator over VALUES / REMOVEFILTERS",
        "complex",
        "partial",
        "Emit iterator pattern; mandatory review of double-aggregation",
        0.68,
        "",
        None,
        None,
    ),
    (
        "Nested LOD",
        "calculation",
        "Composed CALCULATE/iterator chain",
        "very_complex",
        "partial",
        "Cap at ASSISTED; require human review with side-by-side diff",
        0.62,
        "Never AUTO (Section 6 realism constraint)",
        None,
        None,
    ),
    (
        "Table calculation",
        "calculation",
        "WINDOW/OFFSET/INDEX/RANKX functions",
        "complex",
        "partial",
        "Emit window-function pattern with explicit ORDERBY; review addressing/partitioning",
        0.65,
        "",
        "RUNNING_SUM(SUM([Sales]))",
        "SUMX(WINDOW(1, ABS, 0, REL), [Sales])",
    ),
    (
        "Percent of total",
        "calculation",
        "DIVIDE + CALCULATE/ALLSELECTED",
        "medium",
        "full",
        "",
        0.85,
        "",
        None,
        None,
    ),
    (
        "Rank functions",
        "calculation",
        "RANKX / RANK",
        "medium",
        "partial",
        "Verify partitioning scope",
        0.75,
        "",
        None,
        None,
    ),
    (
        "Parameters",
        "calculation",
        "What-if parameter / field parameter",
        "medium",
        "partial",
        "Value parameters -> what-if; field-swap parameters -> field parameters; action-driven need redesign",
        0.72,
        "",
        None,
        None,
    ),
    (
        "Conditional logic (IF/CASE)",
        "calculation",
        "IF / SWITCH",
        "simple",
        "full",
        "",
        0.92,
        None,
        None,
        None,
    ),
    (
        "String/date functions",
        "calculation",
        "DAX text/date functions",
        "simple",
        "full",
        "",
        0.88,
        "Per-function mapping in knowledge base",
        None,
        None,
    ),
    # data layer
    (
        "Relationships (logical layer)",
        "data",
        "Model relationships",
        "simple",
        "full",
        "",
        0.88,
        "Cardinality inferred; many-to-many flagged",
        None,
        None,
    ),
    (
        "Physical joins",
        "data",
        "Power Query merge or model relationship",
        "medium",
        "partial",
        "Prefer star schema: convert join trees to dimensional model where detectable",
        0.72,
        None,
        None,
        None,
    ),
    (
        "Data blending",
        "data",
        "Model relationships across sources (composite model)",
        "complex",
        "partial",
        "Blends with asymmetric granularity -> composite model + review",
        0.60,
        "Blend semantics (left-join-ish) differ from relationships",
        None,
        None,
    ),
    (
        "Extract (.hyper)",
        "data",
        "Import-mode semantic model",
        "simple",
        "full",
        "",
        0.90,
        "Refresh schedule -> scheduled refresh / incremental policy",
        None,
        None,
    ),
    (
        "Live connection",
        "data",
        "DirectQuery / Direct Lake",
        "medium",
        "partial",
        "Validate driver support; Direct Lake when source lands in OneLake",
        0.75,
        None,
        None,
        None,
    ),
    (
        "Custom SQL",
        "data",
        "Power Query native query",
        "medium",
        "partial",
        "Wrap as native query; check folding; parameterized SQL needs M parameters",
        0.70,
        None,
        None,
        None,
    ),
    # security layer
    (
        "User filter (RLS)",
        "security",
        "RLS role with DAX filter",
        "complex",
        "partial",
        "USERNAME()-driven filters -> USERPRINCIPALNAME() role rules; group sets -> AAD groups",
        0.68,
        "",
        "USERNAME() = [Owner]",
        "[Owner] = USERPRINCIPALNAME()",
    ),
    (
        "Data source filter (security)",
        "security",
        "RLS role filter on table",
        "complex",
        "partial",
        "Same as user filter; verify per-datasource scope",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Users/Groups",
        "security",
        "Entra ID (AAD) users/groups",
        "medium",
        "manual",
        "Export user/group matrix; map identities to Entra; identity mapping is an org task",
        0.40,
        None,
        None,
        None,
    ),
    # scheduling layer
    (
        "Extract refresh schedule",
        "scheduling",
        "Dataset scheduled refresh / incremental refresh",
        "simple",
        "partial",
        "Translate cadence; full-vs-incremental analysis from extract config",
        0.78,
        None,
        None,
        None,
    ),
    (
        "Subscription",
        "scheduling",
        "Power BI email subscription",
        "simple",
        "partial",
        "Per-user subscriptions recreated by users or via REST API",
        0.70,
        None,
        None,
        None,
    ),
    (
        "Data-driven alert",
        "scheduling",
        "Power BI alert / Power Automate + DAX query",
        "medium",
        "partial",
        "Complex alert conditions -> Power Automate flow on DAX query result",
        0.62,
        None,
        None,
        None,
    ),
]

SPOTFIRE_MAPPINGS: list[tuple] = [
    ("Analysis file (DXP)", "analysis", "PBIP project", "simple", "full", "", 0.92, "", None, None),
    ("Page", "analysis", "Report page", "simple", "full", "", 0.90, "", None, None),
    (
        "Layout (panels/docking)",
        "analysis",
        "Report page layout (fixed canvas)",
        "medium",
        "partial",
        "Spotfire responsive panels -> fixed canvas placement; document UX delta",
        0.65,
        "",
        None,
        None,
    ),
    (
        "Scatter/bar/line/pie/combo",
        "visualization",
        "Native visuals",
        "simple",
        "full",
        "",
        0.92,
        None,
        None,
        None,
    ),
    ("Cross table", "visualization", "Matrix visual", "simple", "full", "", 0.88, None, None, None),
    (
        "Heat map",
        "visualization",
        "Matrix conditional formatting / heat map visual",
        "medium",
        "partial",
        "Dendrograms/clustering on heat maps are not reproducible natively",
        0.68,
        None,
        None,
        None,
    ),
    (
        "Box plot",
        "visualization",
        "Box & whisker custom visual",
        "medium",
        "partial",
        "Certified custom visual or percentile-based rebuild",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Map chart (layers)",
        "visualization",
        "Azure Map",
        "complex",
        "partial",
        "Multi-layer maps (WMS, feature layers) need redesign; geocoding differs",
        0.55,
        None,
        None,
        None,
    ),
    ("KPI chart", "visualization", "Card/KPI visual", "simple", "full", "", 0.85, None, None, None),
    (
        "Network chart",
        "visualization",
        None,
        "very_complex",
        "manual",
        "Custom visual (e.g. network navigator) or Deneb; review licensing",
        0.30,
        None,
        None,
        None,
    ),
    (
        "Custom visuals (Mods)",
        "visualization",
        None,
        "very_complex",
        "manual",
        "MANUAL always: inventory mod source, rebuild as Deneb/custom visual or native",
        0.20,
        "Section 13 non-goal",
        None,
        None,
    ),
    ("Data table", "data", "Semantic model table", "simple", "full", "", 0.90, None, None, None),
    (
        "Data connection",
        "data",
        "Power Query connection",
        "simple",
        "partial",
        "Driver availability check per connector",
        0.78,
        None,
        None,
        None,
    ),
    (
        "Information link",
        "data",
        "Dataflow Gen2 / Power Query query",
        "complex",
        "partial",
        "Re-extract the underlying SQL from the library; joins/filters/prompts -> M steps; "
        "prompts become parameters",
        0.58,
        None,
        None,
        None,
    ),
    (
        "Data function (TERR/R/Python)",
        "analytics",
        "Fabric notebook / Python in Power Query",
        "very_complex",
        "partial",
        "Aggregation-level stats -> DAX; transformations -> Python notebook in Fabric pipeline; "
        "interactive data functions have no equivalent (document)",
        0.45,
        None,
        None,
        None,
    ),
    (
        "Calculated column",
        "data",
        "DAX calculated column / M custom column",
        "simple",
        "full",
        "",
        0.85,
        None,
        None,
        None,
    ),
    (
        "Transformations (pivot/unpivot/add rows)",
        "data",
        "Power Query transforms",
        "simple",
        "full",
        "",
        0.85,
        None,
        None,
        None,
    ),
    (
        "OVER expressions",
        "calculation",
        "CALCULATE + filter modifiers / window functions",
        "complex",
        "partial",
        "Per-node-navigation mapping; custom hierarchies mandatory review",
        0.65,
        "",
        "Sum([Sales]) OVER (AllPrevious([Axis.X]))",
        "CALCULATE(SUM(Sales[Sales]), FILTER(ALLSELECTED('Date'[Month]), 'Date'[Month] <= MAX('Date'[Month])))",
    ),
    (
        "THEN post-aggregation",
        "calculation",
        "VAR-chained measure",
        "complex",
        "partial",
        "Chain stages as DAX VARs; multi-stage chains reviewed",
        0.60,
        None,
        None,
        None,
    ),
    (
        "Statistical/predictive models",
        "analytics",
        "Fabric Data Science (notebooks, MLflow)",
        "very_complex",
        "manual",
        "Re-train in Fabric notebooks; embed scored output tables into the model",
        0.30,
        None,
        None,
        None,
    ),
    (
        "IronPython scripts (UI automation)",
        "automation",
        None,
        "very_complex",
        "manual",
        "Classify intent: export/email -> Power Automate; property setting -> field parameters/bookmarks; "
        "document API calls per mapping table",
        0.25,
        "Agent-assisted intent classification",
        None,
        None,
    ),
    (
        "Action controls (buttons)",
        "automation",
        "Buttons + bookmarks / navigation",
        "medium",
        "partial",
        "Script-backed actions need redesign per IronPython mapping",
        0.60,
        None,
        None,
        None,
    ),
    (
        "Property controls",
        "automation",
        "Slicers / field parameters / what-if parameters",
        "medium",
        "partial",
        "Document-property writes from scripts have no equivalent",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Document properties",
        "automation",
        "What-if parameters / field parameters",
        "medium",
        "partial",
        "Properties driving expressions -> parameters; driving scripts -> redesign",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Library permissions",
        "security",
        "Workspace roles + app audiences",
        "medium",
        "partial",
        "Folder-level ACLs flatten to workspace roles; document deltas",
        0.60,
        None,
        None,
        None,
    ),
    (
        "Data restrictions (per-user)",
        "security",
        "RLS roles",
        "complex",
        "partial",
        "Personalized information links -> RLS DAX rules on user mapping table",
        0.55,
        None,
        None,
        None,
    ),
    (
        "Scheduled updates (Automation Services)",
        "scheduling",
        "Scheduled refresh / Data pipelines",
        "medium",
        "partial",
        "Automation Services jobs -> Fabric pipeline schedules",
        0.65,
        None,
        None,
        None,
    ),
]

QLIKVIEW_MAPPINGS: list[tuple] = [
    ("Application (.qvw)", "application", "PBIP project", "simple", "full", "", 0.90, None, None, None),
    ("Sheet", "application", "Report page", "simple", "full", "", 0.90, None, None, None),
    (
        "Container object",
        "application",
        "Bookmarks / page navigator / tabs-by-buttons",
        "medium",
        "partial",
        "Containers -> bookmark-swapped visuals or separate pages",
        0.62,
        None,
        None,
        None,
    ),
    (
        "Chart (bar/line/combo/pie/scatter)",
        "visualization",
        "Native visuals",
        "simple",
        "full",
        "",
        0.92,
        None,
        None,
        None,
    ),
    (
        "Pivot table",
        "visualization",
        "Matrix visual",
        "simple",
        "full",
        "",
        0.85,
        "Indented/cyclic groups need review",
        None,
        None,
    ),
    ("Straight table", "visualization", "Table visual", "simple", "full", "", 0.90, None, None, None),
    ("Gauge", "visualization", "Gauge visual", "simple", "full", "", 0.85, None, None, None),
    (
        "Multibox/listbox/current selections",
        "visualization",
        "Slicers + filter pane",
        "simple",
        "partial",
        "Green-white-gray associative UX has no equivalent — document UX delta",
        0.70,
        "Section 13 known limitation",
        None,
        None,
    ),
    (
        "QVD file pipeline",
        "data",
        "Dataflow Gen2 / Lakehouse medallion",
        "complex",
        "partial",
        "QVD layers map to bronze/silver/gold Lakehouse tables; STORE INTO -> dataflow destinations",
        0.62,
        None,
        None,
        None,
    ),
    (
        "Load script",
        "data",
        "Power Query M / Dataflow Gen2",
        "complex",
        "partial",
        "Statement-by-statement conversion; control flow and macros excluded with annotations",
        0.65,
        "",
        "LOAD * FROM data.qvd;",
        "Source = Lakehouse.Contents(...)",
    ),
    (
        "Associative model / synthetic keys",
        "data",
        "Star schema redesign",
        "complex",
        "manual",
        "Detect synthetic keys & circular refs; propose star schema; human modeling decision",
        0.40,
        None,
        None,
        None,
    ),
    (
        "Link tables",
        "data",
        "Bridge tables / relationship redesign",
        "complex",
        "manual",
        "Bridge-table pattern with many-to-many relationships; review",
        0.45,
        None,
        None,
        None,
    ),
    (
        "Set analysis",
        "calculation",
        "CALCULATE filter arguments",
        "complex",
        "partial",
        "AST-translated; dollar expansions and P()/E() reviewed; alternate states MANUAL",
        0.70,
        "",
        "Sum({<Year={2024}>} Sales)",
        "CALCULATE(SUM(Sales[Sales]), Sales[Year] = 2024)",
    ),
    (
        "Variables (expression)",
        "calculation",
        "Measures / what-if parameters",
        "medium",
        "partial",
        "Constant -> what-if; expression variable -> measure; token-splicing variables MANUAL",
        0.62,
        None,
        None,
        None,
    ),
    (
        "Alternate states",
        "calculation",
        None,
        "very_complex",
        "manual",
        "No clean 1:1 DAX equivalent — redesign with bookmarks, field parameters or duplicated "
        "dimension tables for comparison analyses",
        0.30,
        "Section 6 realism constraint",
        None,
        None,
    ),
    (
        "Aggr()",
        "calculation",
        "SUMMARIZE / iterator patterns",
        "complex",
        "partial",
        "Structural translation; nested Aggr MANUAL",
        0.68,
        None,
        None,
        None,
    ),
    (
        "Reload task (Publisher)",
        "automation",
        "Scheduled refresh / Fabric pipeline",
        "medium",
        "partial",
        "Task chains/triggers -> pipeline dependencies",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Macros (VBScript)",
        "automation",
        None,
        "very_complex",
        "manual",
        "MANUAL always: document intent; recommend Power Automate or report redesign",
        0.15,
        "Section 7 constraint",
        None,
        None,
    ),
    (
        "Section Access",
        "security",
        "RLS roles + Entra mapping",
        "complex",
        "partial",
        "ACCESS/USERID/OMIT rows -> RLS roles; OMIT (column hiding) -> OLS; ADMIN concept "
        "has no direct equivalent",
        0.55,
        "",
        "SECTION ACCESS; LOAD * INLINE [...]",
        "RLS role + object-level security",
    ),
    (
        "Document/user permissions",
        "security",
        "Workspace roles",
        "medium",
        "manual",
        "Identity mapping to Entra is an organizational task",
        0.40,
        None,
        None,
        None,
    ),
]

QLIKSENSE_MAPPINGS: list[tuple] = [
    ("App (.qvf)", "app", "PBIP project", "simple", "full", "", 0.90, None, None, None),
    ("Sheet", "app", "Report page", "simple", "full", "", 0.90, None, None, None),
    (
        "Story",
        "app",
        "Bookmark sequence + page snapshots",
        "medium",
        "partial",
        "Snapshot-based stories degrade to bookmark navigation; document delta",
        0.60,
        None,
        None,
        None,
    ),
    (
        "Native visuals",
        "visualization",
        "Native Power BI visuals",
        "simple",
        "full",
        "",
        0.90,
        None,
        None,
        None,
    ),
    (
        "Custom extensions",
        "visualization",
        None,
        "very_complex",
        "manual",
        "MANUAL always: inventory extension JS, map to certified custom visual or rebuild",
        0.20,
        None,
        None,
        None,
    ),
    ("KPI object", "visualization", "KPI / card visual", "simple", "full", "", 0.88, None, None, None),
    (
        "Master measures",
        "data",
        "Model measures (display folder per master folder)",
        "simple",
        "full",
        "",
        0.85,
        "Expression converted via Qlik->DAX engine",
        None,
        None,
    ),
    (
        "Master dimensions",
        "data",
        "Model columns / hierarchies",
        "simple",
        "full",
        "",
        0.85,
        "Drill-down dims -> hierarchies",
        None,
        None,
    ),
    (
        "Variables",
        "data",
        "Measures / what-if parameters",
        "medium",
        "partial",
        "Same policy as QlikView variables",
        0.62,
        None,
        None,
        None,
    ),
    (
        "Load script",
        "data",
        "Power Query M / Dataflow Gen2",
        "complex",
        "partial",
        "Shared converter with QlikView",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Insight Advisor logic",
        "analytics",
        "Copilot for Power BI (conceptual)",
        "complex",
        "manual",
        "Assessment-only: maps conceptually, not mechanically (Section 13)",
        0.20,
        None,
        None,
        None,
    ),
    (
        "Associative engine UX",
        "analytics",
        None,
        "very_complex",
        "manual",
        "No equivalent; document UX delta in client report (Section 13)",
        0.15,
        None,
        None,
        None,
    ),
    (
        "Streams",
        "security",
        "Workspaces + apps + audiences",
        "medium",
        "partial",
        "Stream publish model -> workspace/app distribution",
        0.65,
        None,
        None,
        None,
    ),
    (
        "Section Access",
        "security",
        "RLS roles + Entra mapping",
        "complex",
        "partial",
        "Shared policy with QlikView Section Access",
        0.55,
        None,
        None,
        None,
    ),
]

ALL_SEED_MAPPINGS: dict[str, list[tuple]] = {
    "tableau": TABLEAU_MAPPINGS,
    "spotfire": SPOTFIRE_MAPPINGS,
    "qlikview": QLIKVIEW_MAPPINGS,
    "qliksense": QLIKSENSE_MAPPINGS,
}
